import { createHash } from "node:crypto";
import { CONTRACTS_VERSION } from "@simvehicleapp/contracts";
import { BACKEND_NAME, BACKEND_VERSION, emitWorkflow, headerComment, type WorkflowIr } from "./emit.ts";
import { importFrom, prefix } from "./layout.ts";
import { commentText, jsonNode, pyString, snakeCase } from "./py.ts";
import { CodeWriter, type SourceRange } from "./writer.ts";

/**
 * A whole generation (ADR-0020 §2, ADR-0040 §3): workflow modules, the app module the overlay's `main.py`
 * runs, generated pytest files, source maps, the generation manifest and the AppManifest fragment. Pure:
 * the request in, a file set out, same bytes for the same request.
 */

export const RUNTIME_VERSION = "0.1.0";
export const GENERATED = "app/src/generated/";
export const TESTS = "app/tests/generated/";
export const OWNED_ROOTS = [GENERATED, TESTS];

export interface GenerateRequest {
  project: { slug: string; appName: string; language: string; mqttTopicPrefix: string; traceLevel: "off" | "trigger" | "node" };
  workflows: WorkflowIr[];
  options?: { emitTests?: boolean };
  /** Scenario v1 per workflow for the generated tests (ADR-0022 §8). */
  scenarios?: { workflowId: string; scenario: Record<string, unknown> }[];
}

export interface FileOut {
  path: string;
  content: string;
  sha256: string;
  role: "source" | "header" | "test" | "build" | "config" | "doc";
}

export interface FileSet {
  backend: string;
  runtimeVersion: string;
  files: FileOut[];
  ownedRoots: string[];
  manifestFragment: Record<string, unknown>;
  sourceMaps: { file: string; ranges: SourceRange[] }[];
  diagnostics: never[];
}

const sha256 = (s: string) => createHash("sha256").update(s, "utf8").digest("hex");
const file = (path: string, content: string, role: FileOut["role"]): FileOut => ({ path, content, sha256: sha256(content), role });
const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;

/** Module names: snake_case of the workflow name; a clash gets the first 4 hex of sha256(workflowId). */
export function moduleNames(workflows: WorkflowIr[]): Map<string, string> {
  const out = new Map<string, string>();
  const used = new Set(["app", "workflows", "conftest"]);
  const sorted = [...workflows].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : a.workflowId < b.workflowId ? -1 : 1));
  for (const wf of sorted) {
    const base = snakeCase(wf.name, "workflow");
    let name = base;
    if (used.has(name)) name = `${base}_${sha256(wf.workflowId).slice(0, 4)}`;
    let n = 2;
    while (used.has(name)) name = `${base}_${n++}`;
    used.add(name);
    out.set(wf.workflowId, name);
  }
  return out;
}

export function generateProject(req: GenerateRequest): FileSet {
  const workflows = [...req.workflows].sort((a, b) => (a.workflowId < b.workflowId ? -1 : 1));
  const modules = moduleNames(workflows);
  const byName = [...workflows].sort((a, b) => (modules.get(a.workflowId)! < modules.get(b.workflowId)! ? -1 : 1));
  const files: FileOut[] = [];
  const sourceMaps: FileSet["sourceMaps"] = [];
  const projectHash = `sha256:${sha256(workflows.map((w) => w.irHash).join(","))}`;

  for (const wf of byName) {
    const mod = modules.get(wf.workflowId)!;
    const out = emitWorkflow(wf);
    const path = `${GENERATED}workflows/${mod}.py`;
    files.push(file(path, out.source, "source"));
    sourceMaps.push({ file: path, ranges: out.ranges });
    files.push(file(`${GENERATED}sourcemap/${mod}.map.json`, json({ file: path, workflowId: wf.workflowId, irHash: wf.irHash, ranges: out.ranges }), "config"));
  }
  files.push(file(`${GENERATED}__init__.py`, `${headerComment(projectHash)}\n"""Code generated by SimVehicleApp from the project's workflows."""\n`, "source"));
  files.push(file(`${GENERATED}workflows/__init__.py`, `${headerComment(projectHash)}\n"""One module per workflow; each declares it on the runtime with bind()."""\n`, "source"));

  // App module: what the overlay's main.py runs (ADR-0040 §3).
  const signals = new Map<string, string>();
  for (const wf of workflows) for (const s of wf.signals) signals.set(s.path, s.dataType);
  const level = ["off", "trigger", "node"].includes(req.project.traceLevel) ? req.project.traceLevel : "node";
  const app = new CodeWriter();
  app.line(headerComment(projectHash));
  app.line(`"""The vehicle app ${commentText(req.project.appName)}: ${byName.length} workflow(s) on the SimVehicleApp runtime."""`);
  app.line();
  for (const wf of byName) for (const l of importFrom(".workflows", [modules.get(wf.workflowId)!])) app.line(l);
  app.line();
  app.line(`APP_NAME = ${pyString(req.project.appName)}`);
  app.line(`TRACE_LEVEL = ${pyString(level)}`);
  app.line();
  app.line("#: bind() of every workflow, in a stable order.");
  if (byName.length === 0) app.line("WORKFLOWS = []");
  else {
    app.line("WORKFLOWS = [");
    for (const wf of byName) app.line(`    ${modules.get(wf.workflowId)}.bind,`);
    app.line("]");
  }
  app.line();
  app.line("#: VSS path ⇒ datatype of every signal the workflows use (checked against the vehicle model at start).");
  if (signals.size === 0) app.line("SIGNALS = {}");
  else {
    app.line("SIGNALS = {");
    for (const p of [...signals.keys()].sort()) app.line(`    ${pyString(p)}: ${pyString(signals.get(p)!)},`);
    app.line("}");
  }
  files.push(file(`${GENERATED}app.py`, app.toString(), "source"));

  // Generated tests: each workflow with a scenario runs it on the mock vehicle (ADR-0022 §8).
  if (req.options?.emitTests) {
    const scenarios = new Map((req.scenarios ?? []).map((s) => [s.workflowId, s.scenario]));
    const tests: string[] = [];
    for (const wf of byName) {
      const sc = scenarios.get(wf.workflowId);
      if (!sc) continue;
      const mod = modules.get(wf.workflowId)!;
      const t = new CodeWriter();
      t.line(headerComment(wf.irHash));
      t.line(`"""Scenario ${commentText(String(sc.name ?? ""))} of workflow ${commentText(wf.name)} (contracts scenario v1)."""`);
      t.line();
      for (const l of importFrom("generated.workflows", [mod])) t.line(l);
      t.line("from simvehicleapp_runtime.testing import check_expectations, run_scenario");
      t.line();
      t.stmt(prefix("SCENARIO = ", jsonNode(sc)));
      t.line();
      t.line();
      t.block(`def test_${mod}_scenario_meets_its_expectations() -> None`, () => {
        t.line(`result = run_scenario(${mod}.bind, SCENARIO)`);
        t.line('problems = check_expectations(result, SCENARIO.get("expect"))');
        t.line('assert not problems, "\\n".join(problems)');
      });
      files.push(file(`${TESTS}test_${mod}.py`, t.toString(), "test"));
      tests.push(mod);
    }
    const conf = new CodeWriter();
    conf.line(`# Generated by SimVehicleApp ${BACKEND_NAME} ${BACKEND_VERSION} — DO NOT EDIT.`);
    conf.line('"""Generated tests import the app sources (app/src) and the vendored runtime."""');
    conf.line();
    conf.line("import os");
    conf.line("import sys");
    conf.line();
    conf.line('_SRC = os.path.join(os.path.dirname(__file__), "..", "..", "src")');
    conf.line('for _p in (_SRC, os.path.join(_SRC, "simvehicleapp-runtime")):');
    conf.line("    if os.path.abspath(_p) not in sys.path:");
    conf.line("        sys.path.insert(0, os.path.abspath(_p))");
    files.push(file(`${TESTS}conftest.py`, conf.toString(), "test"));
    if (!tests.length) files.push(file(`${TESTS}README.md`, "No workflow has a scenario yet: SynCode with a scenario adds its test here.\n", "doc"));
  }

  // Generation manifest shipped with the code: deterministic (no generationId/project, ADR-0026).
  const sorted = files.sort((a, b) => (a.path < b.path ? -1 : 1));
  const genManifest = {
    manifestVersion: "1.0.0",
    backend: `python@${BACKEND_VERSION}`,
    runtimeVersion: RUNTIME_VERSION,
    contracts: CONTRACTS_VERSION,
    workflows: workflows.map((w) => ({ workflowId: w.workflowId, revision: w.workflowRevision, irHash: w.irHash })),
    ownedRoots: OWNED_ROOTS,
    files: sorted.map((f) => ({ path: f.path, sha256: f.sha256, role: f.role })),
  };
  sorted.push(file(`${GENERATED}simvehicleapp.gen.json`, json(genManifest), "config"));
  sorted.sort((a, b) => (a.path < b.path ? -1 : 1));

  return {
    backend: `python@${BACKEND_VERSION}`,
    runtimeVersion: RUNTIME_VERSION,
    files: sorted,
    ownedRoots: OWNED_ROOTS,
    manifestFragment: manifestFragment(workflows),
    sourceMaps: sourceMaps.sort((a, b) => (a.file < b.file ? -1 : 1)),
    diagnostics: [],
  };
}

/** AppManifest v3 fragment (ADR-0023 §4): datapoints by path (write wins over read), MQTT topics. */
export function manifestFragment(workflows: WorkflowIr[]): Record<string, unknown> {
  const access = new Map<string, "read" | "write">();
  const reads = new Set<string>();
  const writes = new Set<string>();
  for (const wf of workflows) {
    for (const s of wf.signals) {
      const w = (s as { access?: string[] }).access?.includes("write");
      access.set(s.path, w || access.get(s.path) === "write" ? "write" : "read");
    }
    for (const t of wf.topics) (t.direction === "write" ? writes : reads).add(t.topic);
  }
  return {
    "vehicle-signal-interface": {
      required: [...access.keys()].sort().map((path) => ({ path, access: access.get(path)! })),
      provided: [],
    },
    pubsub: { reads: [...reads].sort(), writes: [...writes].sort() },
  };
}
