/**
 * Generates IR_SPEC.md (M04-T12, ADR-0014): structure tables from schemas/ir.v1.schema.json, the
 * semantics from tools/ir-spec.semantics.md and the golden GW-A IR as the worked example.
 *   bun tools/gen-ir-spec.ts          write
 *   bun tools/gen-ir-spec.ts --check  fail when the committed file is stale
 */
import { readFileSync, writeFileSync } from "node:fs";

type Schema = {
  $id: string;
  description?: string;
  required?: string[];
  properties?: Record<string, Schema & { $ref?: string; enum?: unknown[]; type?: unknown; pattern?: string; items?: Schema }>;
  enum?: unknown[];
  anyOf?: Schema[];
  allOf?: Schema[];
  pattern?: string;
  $defs?: Record<string, Schema>;
};

const root = new URL("../", import.meta.url);
const ir = JSON.parse(readFileSync(new URL("schemas/ir.v1.schema.json", root), "utf8")) as Schema;
const semantics = readFileSync(new URL("tools/ir-spec.semantics.md", root), "utf8").trimEnd();
const example = readFileSync(new URL("fixtures/golden/GW-A/ir.json", root), "utf8").trimEnd();
const defs = ir.$defs ?? {};

/** Short type label of a schema node. */
function label(s: (Schema & { $ref?: string; type?: unknown; items?: Schema }) | undefined): string {
  if (!s) return "";
  if (s.$ref) return s.$ref.replace(/^.*#\/\$defs\//, "").replace(/^urn:simvehicleapp:contracts:([a-z-]+):.*$/, "$1");
  if (s.enum) return s.enum.map((e) => `\`${String(e)}\``).join(", ");
  if (s.type === "array") return `${label(s.items)}[]`;
  if (s.anyOf) return s.anyOf.map((x) => label(x)).join(" \\| ");
  if (s.allOf) return s.allOf.map((x) => (x.pattern ? `matching \`${x.pattern}\`` : label(x))).join(" ");
  if (Array.isArray(s.type)) return s.type.join(" \\| ");
  return typeof s.type === "string" ? s.type : "any";
}

function table(title: string, s: Schema | undefined): string[] {
  if (!s?.properties) return [];
  const req = new Set(s.required ?? []);
  const out = [`### ${title}`, "", "| Field | Type | Required |", "|---|---|---|"];
  for (const [k, v] of Object.entries(s.properties)) out.push(`| \`${k}\` | ${label(v)} | ${req.has(k) ? "yes" : ""} |`);
  return [...out, ""];
}

const triggerOps = (defs.triggerOpcode?.enum ?? []).map(String);
const nodeOps = defs.nodeOpcode?.anyOf ?? [];
const nodeEnum = (nodeOps.find((x) => x.enum)?.enum ?? []).map(String);
const nodePattern = nodeOps.find((x) => x.pattern)?.pattern;

const lines = [
  "# IR v1 specification",
  "",
  "<!-- Generated by tools/gen-ir-spec.ts from schemas/ir.v1.schema.json, tools/ir-spec.semantics.md and fixtures/golden/GW-A/ir.json — do not edit. -->",
  "",
  `Schema \`${ir.$id}\`. ${ir.description ?? ""}`,
  "",
  "## Structure",
  "",
  ...table("Document", ir),
  ...table("Signal (`signals[]`)", defs.signal),
  ...table("Topic (`topics[]`)", defs.topic),
  ...table("State variable (`state[]`)", defs.stateVar),
  ...table("Trigger (`triggers[]`)", defs.trigger),
  ...table("Node (`nodes[]`)", defs.node),
  ...table("Source link (`src`)", defs.src),
  "## Opcodes",
  "",
  `Triggers: ${triggerOps.map((o) => `\`${o}\``).join(", ")}.`,
  "",
  `Nodes: ${nodeEnum.map((o) => `\`${o}\``).join(", ")}${nodePattern ? `, and \`${nodePattern}\` (\`logic.eval\`, \`logic.in_range\`…)` : ""}.`,
  "",
  semantics,
  "",
  "## Example — golden GW-A (Stable Overspeed Warning)",
  "",
  "```json",
  example,
  "```",
  "",
];
const text = lines.join("\n");
const target = new URL("IR_SPEC.md", root);
if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {}
  if (current !== text) {
    console.error("IR_SPEC.md is stale — run: bun tools/gen-ir-spec.ts");
    process.exit(1);
  }
  console.log("IR spec up to date");
} else {
  writeFileSync(target, text);
  console.log("wrote IR_SPEC.md");
}
