// Generates packages/ts/src/types/index.ts from schemas/*.v1.schema.json.
// Usage: bun tools/gen-types.ts [--check]   (--check fails if the committed file is stale)
import { compile } from "json-schema-to-typescript";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { SCHEMA_NAMES, schemasDir } from "../packages/ts/src/schema-names.ts";

const OUT = new URL("../packages/ts/src/types/index.ts", import.meta.url);
const URN = /^urn:simvehicleapp:contracts:([a-z-]+):[^#]+(#.*)?$/;

// Generator-only overrides for shapes json-schema-to-typescript cannot express (recursive unions).
const TS_TYPES: Record<string, string> = {
  IrArgValue: "IrExpr | string | number | boolean | null | IrArgValue[] | { [k: string]: IrArgValue }",
};

const isConditional = (s: unknown) =>
  !!s && typeof s === "object" && Object.keys(s).every((k) => k === "if" || k === "then" || k === "else");

// Prepare a schema for TS generation without changing what it validates:
// - json-schema-to-typescript cannot resolve `urn:` refs; rewrite them to sibling file refs.
// - `if/then` refinements (e.g. int64 values as strings) only narrow validation; dropping them keeps
//   the object's declared properties instead of degrading the type to `{[k: string]: unknown}`.
function prepare(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(prepare);
  if (node && typeof node === "object") {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(node)) {
      if (k === "$id" || k === "if" || k === "then" || k === "else") continue;
      if (k === "allOf" && Array.isArray(v) && v.every(isConditional)) continue;
      const m = k === "$ref" && typeof v === "string" ? URN.exec(v) : null;
      out[k] = m ? `${m[1]}.v1.schema.json${m[2] ?? ""}` : prepare(v);
    }
    const title = out.title as string | undefined;
    if (title && TS_TYPES[title]) return { title, description: out.description, tsType: TS_TYPES[title] };
    return out;
  }
  return node;
}

// Request/message shapes that live in `$defs` but are API bodies on their own.
const EXTRA_DEFS = [
  "diagnostics#/$defs/list",
  "ir#/$defs/expr",
  "generated-fileset#/$defs/generateRequest",
  "toolchain-job#/$defs/request",
  "trace-event#/$defs/runtimeLine",
  "signal-update#/$defs/clientMessage",
  "service-info#/$defs/health",
];

const toPascal = (s: string) => s.replace(/(^|-)([a-z])/g, (_, __, c: string) => c.toUpperCase());

// One synthetic root so each referenced definition is emitted exactly once.
const root = {
  title: "ContractsRoot",
  type: "object",
  additionalProperties: false,
  properties: Object.fromEntries([
    ...SCHEMA_NAMES.filter((n) => n !== "common").map((n) => [toPascal(n), { $ref: `${n}.v1.schema.json` }]),
    ...EXTRA_DEFS.map((r) => [toPascal(r.replace("#/$defs/", "-")), { $ref: r.replace("#", ".v1.schema.json#") }]),
  ]),
};

const files = new Map(
  SCHEMA_NAMES.map((n) => [`${n}.v1.schema.json`, prepare(JSON.parse(readFileSync(`${schemasDir}${n}.v1.schema.json`, "utf8")))]),
);

const ts = await compile(root as never, "ContractsRoot", {
  cwd: schemasDir,
  bannerComment: "/* Generated by tools/gen-types.ts from schemas/*.v1.schema.json — DO NOT EDIT. */",
  additionalProperties: false,
  unreachableDefinitions: false,
  strictIndexSignatures: true,
  format: true,
  $refOptions: {
    resolve: {
      contracts: {
        order: 1,
        canRead: (f: { url: string }) => files.has(f.url.split("/").pop()!.split("#")[0]!),
        read: (f: { url: string }) => JSON.stringify(files.get(f.url.split("/").pop()!.split("#")[0]!)),
      },
    },
  } as never,
});

const current = (() => {
  try {
    return readFileSync(OUT, "utf8");
  } catch {
    return "";
  }
})();

if (process.argv.includes("--check")) {
  if (current !== ts) {
    console.error("packages/ts/src/types/index.ts is stale — run `bun run gen`.");
    process.exit(1);
  }
  console.log("types up to date");
} else {
  mkdirSync(new URL(".", OUT), { recursive: true });
  writeFileSync(OUT, ts);
  console.log(`wrote ${OUT.pathname}`);
}
