/**
 * Generates DIAGNOSTICS_CATALOG.md from schemas/diagnostics-catalog.v1.json (ADR-0016 §2).
 *   bun tools/gen-diagnostics-doc.ts          write
 *   bun tools/gen-diagnostics-doc.ts --check  fail when the committed file is stale
 */
import { readFileSync, writeFileSync } from "node:fs";

interface Entry {
  code: string;
  severity: string;
  stage: string;
  title: string;
  since: string;
  adr?: string;
  deprecated?: boolean | string;
}

const root = new URL("../", import.meta.url);
const catalog = JSON.parse(readFileSync(new URL("schemas/diagnostics-catalog.v1.json", root), "utf8")) as {
  catalogVersion: string;
  codes: Entry[];
};
const STAGE_ORDER = ["parse", "structural", "block-config", "vehicle-model", "types", "units", "control-flow", "lint", "backend", "codegen", "workspace", "build", "test", "run", "runtime", "license"];
const rank = (s: string) => (STAGE_ORDER.indexOf(s) === -1 ? STAGE_ORDER.length : STAGE_ORDER.indexOf(s));
const stages = [...new Set(catalog.codes.map((c) => c.stage))].sort((a, b) => rank(a) - rank(b) || a.localeCompare(b));

const lines = [
  "# Diagnostics catalog",
  "",
  `<!-- Generated by tools/gen-diagnostics-doc.ts from schemas/diagnostics-catalog.v1.json — do not edit. -->`,
  "",
  `Catalog ${catalog.catalogVersion} · ${catalog.codes.length} codes. Codes are public API (ADR-0016 §2): never renamed or removed; retired codes are flagged \`deprecated\`.`,
  "",
];
for (const stage of stages) {
  lines.push(`## ${stage}`, "", "| Code | Severity | Title | Since | ADR |", "|---|---|---|---|---|");
  for (const c of catalog.codes.filter((x) => x.stage === stage).sort((a, b) => a.code.localeCompare(b.code))) {
    const title = c.deprecated ? `~~${c.title}~~ (deprecated${typeof c.deprecated === "string" ? `: ${c.deprecated}` : ""})` : c.title;
    lines.push(`| \`${c.code}\` | ${c.severity} | ${title} | ${c.since} | ${c.adr ?? ""} |`);
  }
  lines.push("");
}
const text = lines.join("\n");
const target = new URL("DIAGNOSTICS_CATALOG.md", root);
if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {}
  if (current !== text) {
    console.error("DIAGNOSTICS_CATALOG.md is stale — run: bun tools/gen-diagnostics-doc.ts");
    process.exit(1);
  }
  console.log("diagnostics doc up to date");
} else {
  writeFileSync(target, text);
  console.log(`wrote DIAGNOSTICS_CATALOG.md (${catalog.codes.length} codes)`);
}
