import {
  a2aCancelTaskTool,
  a2aDeletePushNotificationTool,
  a2aGetAgentCardTool,
  a2aGetPushNotificationTool,
  a2aGetTaskTool,
  a2aResubscribeTool,
  a2aSendMessageTool,
  a2aSetPushNotificationTool,
} from '@/tools/a2a'
import {
  deploymentsDeployTool,
  deploymentsGetVersionTool,
  deploymentsListVersionsTool,
  deploymentsPromoteTool,
  deploymentsUndeployTool,
} from '@/tools/deployments'
import { enrichmentRunTool } from '@/tools/enrichment'
import {
  fileAppendTool,
  fileCompressTool,
  fileDecompressTool,
  fileFetchTool,
  fileGetContentTool,
  fileGetTool,
  fileManageSharingTool,
  fileParserV2Tool,
  fileParserV3Tool,
  fileParseTool,
  fileReadTool,
  fileWriteTool,
} from '@/tools/file'
import { functionExecuteTool } from '@/tools/function'
import { guardrailsValidateTool } from '@/tools/guardrails'
import { httpRequestTool, webhookRequestTool } from '@/tools/http'
import { imageGenerateTool } from '@/tools/image'
import {
  knowledgeCreateDocumentTool,
  knowledgeDeleteChunkTool,
  knowledgeDeleteDocumentTool,
  knowledgeGetConnectorTool,
  knowledgeGetDocumentTool,
  knowledgeListChunksTool,
  knowledgeListConnectorsTool,
  knowledgeListDocumentsTool,
  knowledgeListTagsTool,
  knowledgeSearchTool,
  knowledgeTriggerSyncTool,
  knowledgeUpdateChunkTool,
  knowledgeUploadChunkTool,
  knowledgeUpsertDocumentTool,
} from '@/tools/knowledge'
import { llmChatTool } from '@/tools/llm'
import {
  logsGetExecutionTool,
  logsGetRunDetailsTool,
  logsGetTool,
  logsQueryRunsTool,
  logsQueryTool,
} from '@/tools/logs'
import { memoryAddTool, memoryDeleteTool, memoryGetAllTool, memoryGetTool } from '@/tools/memory'
import { openAIEmbeddingsTool, openAIImageTool } from '@/tools/openai'
import { searchTool } from '@/tools/search'
import {
  tableBatchInsertRowsTool,
  tableCreateTool,
  tableDeleteRowsByFilterTool,
  tableDeleteRowTool,
  tableGetRowTool,
  tableGetSchemaTool,
  tableInsertRowTool,
  tableListTool,
  tableQueryRowsTool,
  tableUpdateRowsByFilterTool,
  tableUpdateRowTool,
  tableUpsertRowTool,
} from '@/tools/table'
import { thinkingTool } from '@/tools/thinking'
import {
  azureTtsTool,
  cartesiaTtsTool,
  deepgramTtsTool,
  elevenLabsTtsUnifiedTool,
  googleTtsTool,
  openaiTtsTool,
  playhtTtsTool,
} from '@/tools/tts'
import type { ToolConfig } from '@/tools/types'
import {
  falaiVideoTool,
  lumaVideoTool,
  minimaxVideoTool,
  runwayVideoTool,
  veoVideoTool,
} from '@/tools/video'
import { visionTool, visionToolV2 } from '@/tools/vision'
import { workflowExecutorTool } from '@/tools/workflow'

// Registry of all available tools
export const tools: Record<string, ToolConfig> = {
  a2a_cancel_task: a2aCancelTaskTool,
  a2a_delete_push_notification: a2aDeletePushNotificationTool,
  a2a_get_agent_card: a2aGetAgentCardTool,
  a2a_get_push_notification: a2aGetPushNotificationTool,
  a2a_get_task: a2aGetTaskTool,
  a2a_resubscribe: a2aResubscribeTool,
  a2a_send_message: a2aSendMessageTool,
  a2a_set_push_notification: a2aSetPushNotificationTool,
  openai_embeddings: openAIEmbeddingsTool,
  http_request: httpRequestTool,
  webhook_request: webhookRequestTool,
  llm_chat: llmChatTool,
  function_execute: functionExecuteTool,
  vision_tool: visionTool,
  vision_tool_v2: visionToolV2,
  file_parser: fileParseTool,
  file_parser_v2: fileParserV2Tool,
  file_parser_v3: fileParserV3Tool,
  file_append: fileAppendTool,
  file_compress: fileCompressTool,
  file_decompress: fileDecompressTool,
  file_fetch: fileFetchTool,
  file_get: fileGetTool,
  file_get_content: fileGetContentTool,
  file_read: fileReadTool,
  file_manage_sharing: fileManageSharingTool,
  file_write: fileWriteTool,
  guardrails_validate: guardrailsValidateTool,
  logs_query: logsQueryTool,
  logs_query_runs: logsQueryRunsTool,
  logs_get: logsGetTool,
  logs_get_execution: logsGetExecutionTool,
  logs_get_run_details: logsGetRunDetailsTool,
  deployments_deploy: deploymentsDeployTool,
  deployments_get_version: deploymentsGetVersionTool,
  deployments_list_versions: deploymentsListVersionsTool,
  deployments_promote: deploymentsPromoteTool,
  deployments_undeploy: deploymentsUndeployTool,
  enrichment_run: enrichmentRunTool,
  thinking_tool: thinkingTool,
  memory_add: memoryAddTool,
  memory_get: memoryGetTool,
  memory_get_all: memoryGetAllTool,
  memory_delete: memoryDeleteTool,
  knowledge_search: knowledgeSearchTool,
  knowledge_upload_chunk: knowledgeUploadChunkTool,
  knowledge_create_document: knowledgeCreateDocumentTool,
  knowledge_list_tags: knowledgeListTagsTool,
  knowledge_list_documents: knowledgeListDocumentsTool,
  knowledge_get_document: knowledgeGetDocumentTool,
  knowledge_delete_document: knowledgeDeleteDocumentTool,
  knowledge_list_chunks: knowledgeListChunksTool,
  knowledge_update_chunk: knowledgeUpdateChunkTool,
  knowledge_delete_chunk: knowledgeDeleteChunkTool,
  knowledge_list_connectors: knowledgeListConnectorsTool,
  knowledge_get_connector: knowledgeGetConnectorTool,
  knowledge_trigger_sync: knowledgeTriggerSyncTool,
  knowledge_upsert_document: knowledgeUpsertDocumentTool,
  search_tool: searchTool,
  tts_openai: openaiTtsTool,
  tts_deepgram: deepgramTtsTool,
  tts_elevenlabs: elevenLabsTtsUnifiedTool,
  tts_cartesia: cartesiaTtsTool,
  tts_google: googleTtsTool,
  tts_azure: azureTtsTool,
  tts_playht: playhtTtsTool,
  video_runway: runwayVideoTool,
  video_veo: veoVideoTool,
  video_luma: lumaVideoTool,
  video_minimax: minimaxVideoTool,
  video_falai: falaiVideoTool,
  image_generate: imageGenerateTool,
  openai_image: openAIImageTool,
  workflow_executor: workflowExecutorTool,
  table_create: tableCreateTool,
  table_list: tableListTool,
  table_insert_row: tableInsertRowTool,
  table_batch_insert_rows: tableBatchInsertRowsTool,
  table_upsert_row: tableUpsertRowTool,
  table_update_row: tableUpdateRowTool,
  table_update_rows_by_filter: tableUpdateRowsByFilterTool,
  table_delete_row: tableDeleteRowTool,
  table_delete_rows_by_filter: tableDeleteRowsByFilterTool,
  table_query_rows: tableQueryRowsTool,
  table_get_row: tableGetRowTool,
  table_get_schema: tableGetSchemaTool,
}
