'use client'

import { useState } from 'react'
import { Badge, Button, Checkbox, toast } from '@/components/emcn'
import type { SvProject } from '@/lib/api/contracts/sv'
import { GeneratedFiles } from '@/app/workspace/[workspaceId]/vehicle-projects/components/generated-files'
import { useUpdateSvProjectWorkflows } from '@/hooks/queries/sv-projects'

const STATUS = {
  creating: { label: 'Preparing…', variant: 'amber' },
  ready: { label: 'Ready', variant: 'green' },
  failed: { label: 'Failed', variant: 'red' },
} as const

interface ProjectCardProps {
  project: SvProject
  workflows: { id: string; name: string }[]
  canEdit: boolean
}

/** One project: status, assigned workflows (checkboxes) and its generated files. */
export function ProjectCard({ project, workflows, canEdit }: ProjectCardProps) {
  const updateWorkflows = useUpdateSvProjectWorkflows()
  const [showFiles, setShowFiles] = useState(false)
  const assigned = new Set(project.workflows.filter((w) => w.enabled).map((w) => w.simWorkflowId))
  const status = STATUS[project.status]

  const toggle = (workflowId: string, on: boolean) => {
    const next = new Set(assigned)
    if (on) next.add(workflowId)
    else next.delete(workflowId)
    updateWorkflows.mutate(
      {
        projectId: project.id,
        workflowIds: workflows.map((w) => w.id).filter((id) => next.has(id)),
      },
      { onError: (e) => toast.error(e.message) }
    )
  }

  return (
    <div
      data-sv='project'
      data-sv-project={project.slug}
      className='flex flex-col gap-3 rounded-lg border border-[var(--border)] p-3'
    >
      <div className='flex items-center gap-2'>
        <span className='font-medium text-[14px] text-[var(--text-primary)]'>{project.name}</span>
        <Badge variant={status.variant} size='sm' data-sv='project-status'>
          {status.label}
        </Badge>
        <span className='text-[12px] text-[var(--text-muted)]'>
          {`/workspace/projects/${project.slug} · C++ · VSS ${project.vssRelease} · ${project.appName}`}
        </span>
        <div className='ml-auto'>
          <Button
            variant='ghost'
            size='sm'
            data-sv='project-files-toggle'
            disabled={project.status !== 'ready'}
            onClick={() => setShowFiles((v) => !v)}
          >
            {showFiles ? 'Hide files' : 'Generated files'}
          </Button>
        </div>
      </div>
      {project.status === 'failed' && project.statusMessage && (
        <p className='text-[12px] text-[var(--text-error)]'>{project.statusMessage}</p>
      )}
      <div className='flex flex-col gap-1'>
        <span className='text-[12px] text-[var(--text-secondary)]'>
          Workflows generated by SynCode
        </span>
        {workflows.length === 0 ? (
          <span className='text-[12px] text-[var(--text-muted)]'>
            No workflows in this workspace
          </span>
        ) : (
          <div className='flex flex-wrap gap-x-4 gap-y-1'>
            {workflows.map((w) => (
              <label
                key={w.id}
                htmlFor={`sv-project-${project.id}-${w.id}`}
                className='flex items-center gap-1.5 text-[13px] text-[var(--text-primary)]'
              >
                <Checkbox
                  id={`sv-project-${project.id}-${w.id}`}
                  size='sm'
                  aria-label={`Generate ${w.name}`}
                  data-sv-workflow={w.id}
                  checked={assigned.has(w.id)}
                  disabled={!canEdit || updateWorkflows.isPending}
                  onCheckedChange={(v) => toggle(w.id, v === true)}
                />
                {w.name}
              </label>
            ))}
          </div>
        )}
      </div>
      {showFiles && <GeneratedFiles projectId={project.id} />}
    </div>
  )
}
