import type { Generation, Project } from "./repo.ts";

/**
 * What the orchestrator adds to a project export (ADR-0031 §1, §5, M09-T06): the workflow graphs the
 * project was generated from (re-importable, M09-T08), the generation it holds, the license, and the
 * notices. Everything else is the project folder as the workspace zips it. Deterministic: no clock.
 */

const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;

export function exportExtras(project: Project, generation: Generation | null, license: unknown | null): { path: string; content: string }[] {
  const files: { path: string; content: string }[] = [];
  for (const graph of generation?.request.graphs ?? []) {
    const id = String(graph.workflowId ?? "");
    if (/^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$/.test(id)) files.push({ path: `.simvehicleapp/workflows/${id}.graph.json`, content: json(graph) });
  }
  if (generation) {
    files.push({
      path: ".simvehicleapp/generation.json",
      content: json({
        generationId: generation.id,
        state: generation.state,
        verification: generation.verification,
        workflows: generation.workflows,
        ...(generation.backend ? { backend: generation.backend } : {}),
        ...(generation.compilerVersion ? { compilerVersion: generation.compilerVersion } : {}),
        ...(generation.modelHash ? { modelHash: generation.modelHash } : {}),
      }),
    });
  }
  if (license) files.push({ path: ".simvehicleapp/license.json", content: json(license) });
  files.push({ path: "README.SIMVEHICLE.md", content: readme(project, generation) }, { path: "NOTICE", content: notice(project) }, { path: "THIRD-PARTY-NOTICES", content: thirdParty(project) });
  return files;
}

/** What differs between a C++ and a Python project in the export (ADR-0031 §5; Python: ADR-0040). */
const LANGUAGE = {
  cpp: {
    app: "A Velocitas C++ vehicle app (eclipse-velocitas/vehicle-app-cpp-template)",
    own: "`app/src/user/`",
    template: "eclipse-velocitas/vehicle-app-cpp-template",
    build: `In the template's devcontainer (or any Velocitas C++ environment):

\`\`\`sh
velocitas init
./install_dependencies.sh
./build.sh
build/bin/app_generated_tests   # the scenarios saved with the workflows
\`\`\``,
    run: "build/bin/app",
    thirdParty: `Included in this project:
- eclipse-velocitas/vehicle-app-cpp-template @ 275e858 — Apache-2.0 (template files, app/Dockerfile,
  .devcontainer, build scripts).
- COVESA Vehicle Signal Specification document (app/vss/) — MPL-2.0, unmodified.

Fetched at build time (Conan / CMake), not included:
- eclipse-velocitas vehicle-app-sdk 0.7.1 — Apache-2.0
- nlohmann/json 3.11.3 — MIT
- fmt 11.1.1 — MIT
- gRPC, abseil, c-ares, re2, protobuf, OpenSSL, zlib — Apache-2.0 / BSD-3-Clause / MIT / Zlib
  (transitive dependencies of the SDK)
- Eclipse Paho MQTT C/C++ — EPL-2.0 OR EDL-1.0
- googletest — BSD-3-Clause (tests only)
`,
  },
  python: {
    app: "A Velocitas Python vehicle app (eclipse-velocitas/vehicle-app-python-template)",
    own: "`app/src/user_hooks.py`",
    template: "eclipse-velocitas/vehicle-app-python-template",
    build: `In the template's devcontainer (or any Python 3.10+ with the Velocitas CLI):

\`\`\`sh
velocitas init
pip3 install -r app/requirements.txt -r app/tests/requirements.txt
PYTHONPATH=app/src:app/src/simvehicleapp-runtime python3 -m pytest app/tests/generated   # the saved scenarios
\`\`\``,
    run: "python3 app/src/main.py",
    thirdParty: `Included in this project:
- eclipse-velocitas/vehicle-app-python-template @ e7082f7 — Apache-2.0 (template files, app/Dockerfile,
  .devcontainer, requirements); app/src/main.py is derived from the template's (header kept).
- COVESA Vehicle Signal Specification document (app/vss/) — MPL-2.0, unmodified.

Installed with pip from app/requirements.txt, not included:
- eclipse-velocitas velocitas-sdk 0.15.7 — Apache-2.0
- grpcio, protobuf, paho-mqtt, opentelemetry, aiohttp and their dependencies — Apache-2.0 / BSD-3-Clause /
  EPL-2.0 OR EDL-1.0 / MIT (see app/requirements.txt)
- pytest — MIT (tests only)
`,
  },
} as const;
const languageOf = (p: Project) => LANGUAGE[p.language === "python" ? "python" : "cpp"];

function readme(p: Project, g: Generation | null): string {
  const lang = languageOf(p);
  const workflows = (g?.workflows ?? []).map((w) => `- \`${w.workflowId}\` (revision ${w.revision}, ${w.irHash})`).join("\n") || "- (no SynCode yet)";
  return `# ${p.name} — exported from SimVehicleApp

${lang.app} generated by SimVehicleApp
from no-code workflows. App \`${p.appName}\`, VSS ${p.vssRelease}.

Workflows:
${workflows}

## Layout
- \`app/src/generated/\`, \`app/tests/generated/\` — generated from the workflows (DO NOT EDIT: SynCode
  rewrites them; edit the workflow, or ${lang.own} for your own code).
- \`app/src/simvehicleapp-runtime/\` — the SimVehicleApp runtime the generated code runs on (Apache-2.0).
- \`app/vss/\` — the VSS ${p.vssRelease} document the vehicle model is generated from (COVESA, MPL-2.0).
- \`.simvehicleapp/workflows/*.graph.json\` — the workflows (WorkflowGraph v1), importable in SimVehicleApp.
- Everything else comes from the Velocitas template.

## Build
${lang.build}

Container image of the app (the template's Dockerfile): \`docker build -f app/Dockerfile .\`

Run against a KUKSA databroker (\`sdv.databroker.v1\`, e.g. kuksa-databroker 0.5.0 with
\`--enable-databroker-v1\`) and an MQTT broker:

\`\`\`sh
SDV_MIDDLEWARE_TYPE=native SDV_VEHICLEDATABROKER_ADDRESS=grpc://127.0.0.1:55555 \\
SDV_MQTT_ADDRESS=mqtt://127.0.0.1:1883 SV_TRACE_LEVEL=off ${lang.run}
\`\`\`

\`SV_TRACE_LEVEL\` (off, trigger, node) can lower the trace the app prints as \`SVTRACE {…}\` lines.
`;
}

const notice = (p: Project) => `This project was generated by SimVehicleApp.
Copyright 2026 SimVehicleApp contributors.

- Generated code (app/src/generated, app/tests/generated) and the SimVehicleApp runtime
  (app/src/simvehicleapp-runtime): Apache License, Version 2.0.
- Based on ${languageOf(p).template} (Copyright (c) 2022-2025 Contributors to the
  Eclipse Foundation, Apache-2.0); template files keep their original headers and license.
- See THIRD-PARTY-NOTICES for the components the project uses.
`;

const thirdParty = (p: Project) => `Third-party components

${languageOf(p).thirdParty}`;
