/* Generated by tools/gen-types.ts from schemas/*.v1.schema.json — DO NOT EDIT. */

/**
 * An expression tree, an IR id (signal/topic/state/node), a plain literal, or a list/record of argValues. Plain records must not use `$`-prefixed keys (those are reserved for expressions).
 */
export type IrArgValue =
  IrExpr | string | number | boolean | null | IrArgValue[] | {[k: string]: IrArgValue} | undefined;
/**
 * @minItems 1
 */
export type OwnedRoots = [
  string & {
    [k: string]: unknown | undefined;
  },
  ...(string & {
    [k: string]: unknown | undefined;
  })[]
];
/**
 * Any JSON value. Producers MUST encode int64/uint64 as decimal strings.
 */
export type JsonValue = string | number | boolean | null | unknown[] | {};
export type ScenarioInput =
  | {
      t: number;
      path: string;
      value: JsonValue;
    }
  | {
      t: number;
      topic: string;
      value: JsonValue;
    };
export type WorkflowPatchOp =
  | {
      op: "add_block";
      ref: string;
      type: string;
      name?: string;
      props: {};
      /**
       * Existing block id or a `ref` introduced by an earlier add_block in the same patch.
       */
      parentId?: string;
      position?:
        | "auto"
        | {
            x: number;
            y: number;
          };
    }
  | {
      op: "connect";
      /**
       * Existing block id or a `ref` introduced by an earlier add_block in the same patch.
       */
      from: string;
      fromHandle: string;
      /**
       * Existing block id or a `ref` introduced by an earlier add_block in the same patch.
       */
      to: string;
      toHandle?: string;
    }
  | {
      op: "set_props";
      /**
       * Existing block id or a `ref` introduced by an earlier add_block in the same patch.
       */
      block: string;
      props: {};
    }
  | {
      op: "remove_block";
      /**
       * Existing block id or a `ref` introduced by an earlier add_block in the same patch.
       */
      block: string;
    };
export type IrExpr = IrExprConst | IrExprRef | IrExprSignal | IrExprState | IrExprTemplate | IrExprOp;
export type SignalClientMessage =
  | {
      op: "subscribe";
      /**
       * @minItems 1
       */
      paths: [string, ...string[]];
    }
  | {
      op: "unsubscribe";
      paths?: string[];
    }
  | {
      op: "set";
      path: string;
      value: JsonValue;
      /**
       * `value` = current value, `target` = actuator target (kuksa.val.v1).
       */
      field: "value" | "target";
    };

export interface ContractsRoot {
  Diagnostics?: DiagnosticV1;
  DiagnosticsCatalog?: DiagnosticsCatalogV1;
  WorkflowGraph?: WorkflowGraphV1;
  Ir?: IRV1;
  BlockSpec?: BlockSpecV1;
  GeneratedFileset?: GeneratedFileSetV1;
  BackendCapabilities?: BackendCapabilitiesV1;
  ToolchainJob?: ToolchainJobV1;
  TraceEvent?: TraceEventV1;
  LogLine?: LogLineV1;
  SignalUpdate?: SignalUpdateV1;
  Scenario?: ScenarioV1;
  WorkflowPatch?: WorkflowPatchV1;
  GenerationManifest?: GenerationManifestV1;
  License?: LicenseV1;
  ServiceInfo?: ServiceInfoV1;
  DiagnosticsList?: DiagnosticList;
  IrExpr?: IrExpr;
  GeneratedFilesetGenerateRequest?: GenerateRequest;
  ToolchainJobRequest?: ToolchainJobRequest;
  TraceEventRuntimeLine?: TraceRuntimeLine;
  SignalUpdateClientMessage?: SignalClientMessage;
  ServiceInfoHealth?: ServiceHealth;
}
/**
 * One diagnostic (ADR-0016 §1). `code` is public API: never renamed or removed. `message` is rendered from `code` + `data`.
 */
export interface DiagnosticV1 {
  code: string;
  severity: "error" | "warning" | "info";
  stage:
    | "parse"
    | "structural"
    | "block-config"
    | "vehicle-model"
    | "types"
    | "units"
    | "control-flow"
    | "lint"
    | "backend"
    | "codegen"
    | "workspace"
    | "build"
    | "test"
    | "run"
    | "runtime"
    | "license";
  blockId?: string;
  field?: string;
  nodeId?: string;
  workflowId?: string;
  message: string;
  suggestion?: string;
  docs: string;
  data?: {};
}
/**
 * Catalog of public diagnostic codes (ADR-0016 §2). Codes are append-only; retire with `deprecated`.
 */
export interface DiagnosticsCatalogV1 {
  catalogVersion: string;
  /**
   * @minItems 1
   */
  codes: [
    {
      code: string;
      severity: "error" | "warning" | "info";
      stage:
        | "parse"
        | "structural"
        | "block-config"
        | "vehicle-model"
        | "types"
        | "units"
        | "control-flow"
        | "lint"
        | "backend"
        | "codegen"
        | "workspace"
        | "build"
        | "test"
        | "run"
        | "runtime"
        | "license";
      title: string;
      since: string;
      deprecated?: boolean;
      adr?: string;
    },
    ...{
      code: string;
      severity: "error" | "warning" | "info";
      stage:
        | "parse"
        | "structural"
        | "block-config"
        | "vehicle-model"
        | "types"
        | "units"
        | "control-flow"
        | "lint"
        | "backend"
        | "codegen"
        | "workspace"
        | "build"
        | "test"
        | "run"
        | "runtime"
        | "license";
      title: string;
      since: string;
      deprecated?: boolean;
      adr?: string;
    }[]
  ];
}
/**
 * Canonical, Sim-agnostic workflow graph: compiler input (analysis/06 §1.1, ADR-0013). Edges are control flow only; data flows through `<…>` references inside props. Size limits (GRAPH_TOO_LARGE) are enforced by the compiler, not here.
 */
export interface WorkflowGraphV1 {
  graphVersion: string & {
    [k: string]: unknown | undefined;
  };
  workflowId: string;
  revision: number;
  name: string;
  vss: {
    release: string;
    /**
     * Prefixed content hash.
     */
    modelHash?: string;
  };
  variables: GraphVariable[];
  blocks: GraphBlock[];
  edges: GraphEdge[];
}
export interface GraphVariable {
  name: string;
  /**
   * VSS datatypes plus internal types (ADR-0015 §1).
   */
  type:
    | (
        | "boolean"
        | "int8"
        | "int16"
        | "int32"
        | "int64"
        | "uint8"
        | "uint16"
        | "uint32"
        | "uint64"
        | "float"
        | "double"
        | "string"
        | "boolean[]"
        | "int8[]"
        | "int16[]"
        | "int32[]"
        | "int64[]"
        | "uint8[]"
        | "uint16[]"
        | "uint32[]"
        | "uint64[]"
        | "float[]"
        | "double[]"
        | "string[]"
      )
    | ("duration" | "timestamp" | "json");
  initial: unknown;
}
export interface GraphBlock {
  id: string;
  type: string;
  name: string;
  /**
   * Block properties keyed by BlockSpec prop name. Values are literals or SVX expression strings; int64/uint64 literals are decimal strings.
   */
  props: {};
  /**
   * Container block id (repeat/while/parallel) or null for top level.
   */
  parentId?: string | null;
  blockVersion?: number;
}
export interface GraphEdge {
  id: string;
  from: string;
  fromHandle: string;
  to: string;
  toHandle: string;
}
/**
 * Canonical IR v1 (ADR-0014, analysis/06 §2): control graph via `next` + expression trees. No timestamps. irHash = sha256(canonical(IR without irHash)). Adding an opcode is a minor bump.
 */
export interface IRV1 {
  irVersion: string & {
    [k: string]: unknown | undefined;
  };
  compilerVersion: string;
  workflowId: string;
  workflowRevision: number;
  /**
   * PascalCase identifier usable by every backend.
   */
  name: string;
  /**
   * Prefixed content hash.
   */
  modelHash: string;
  /**
   * Prefixed content hash.
   */
  sourceGraphHash: string;
  /**
   * Prefixed content hash.
   */
  irHash: string;
  signals: IrSignal[];
  topics: IrTopic[];
  state: IrStateVar[];
  triggers: IrTrigger[];
  nodes: IrNode[];
  diagnostics: DiagnosticV1[];
}
export interface IrSignal {
  id: string;
  path: string;
  vssType: "sensor" | "actuator" | "attribute";
  /**
   * A VSS scalar type or its variable-length array form `T[]`.
   */
  dataType:
    | "boolean"
    | "int8"
    | "int16"
    | "int32"
    | "int64"
    | "uint8"
    | "uint16"
    | "uint32"
    | "uint64"
    | "float"
    | "double"
    | "string"
    | "boolean[]"
    | "int8[]"
    | "int16[]"
    | "int32[]"
    | "int64[]"
    | "uint8[]"
    | "uint16[]"
    | "uint32[]"
    | "uint64[]"
    | "float[]"
    | "double[]"
    | "string[]";
  /**
   * VSS unit symbol (units.yaml key); null = dimensionless.
   */
  unit: string | null;
  /**
   * @minItems 1
   */
  access: ["read" | "subscribe" | "write", ...("read" | "subscribe" | "write")[]];
}
export interface IrTopic {
  id: string;
  topic: string;
  direction: "read" | "write";
}
export interface IrStateVar {
  id: string;
  name: string;
  /**
   * VSS datatypes plus internal types (ADR-0015 §1).
   */
  type:
    | (
        | "boolean"
        | "int8"
        | "int16"
        | "int32"
        | "int64"
        | "uint8"
        | "uint16"
        | "uint32"
        | "uint64"
        | "float"
        | "double"
        | "string"
        | "boolean[]"
        | "int8[]"
        | "int16[]"
        | "int32[]"
        | "int64[]"
        | "uint8[]"
        | "uint16[]"
        | "uint32[]"
        | "uint64[]"
        | "float[]"
        | "double[]"
        | "string[]"
      )
    | ("duration" | "timestamp" | "json");
  initial: unknown;
}
export interface IrTrigger {
  id: string;
  opcode: "event.app_start" | "event.signal_changed" | "event.timer" | "event.condition" | "event.mqtt_message";
  signal?: string;
  topic?: string;
  props: {
    [k: string]: IrArgValue | undefined;
  };
  concurrency?: IrConcurrency;
  outputs: IrOutputs;
  entry: string | null;
  src: IrSrc;
}
export interface IrConcurrency {
  policy: "restart" | "ignore" | "queue" | "parallel";
  queueMax?: number;
  maxRuns?: number;
}
export interface IrOutputs {
  [k: string]: IrOutputSpec | undefined;
}
export interface IrOutputSpec {
  /**
   * VSS datatypes plus internal types (ADR-0015 §1).
   */
  type:
    | (
        | "boolean"
        | "int8"
        | "int16"
        | "int32"
        | "int64"
        | "uint8"
        | "uint16"
        | "uint32"
        | "uint64"
        | "float"
        | "double"
        | "string"
        | "boolean[]"
        | "int8[]"
        | "int16[]"
        | "int32[]"
        | "int64[]"
        | "uint8[]"
        | "uint16[]"
        | "uint32[]"
        | "uint64[]"
        | "float[]"
        | "double[]"
        | "string[]"
      )
    | ("duration" | "timestamp" | "json");
  /**
   * VSS unit symbol (units.yaml key); null = dimensionless.
   */
  unit?: string | null;
}
export interface IrSrc {
  blockId: string;
  inserted?: boolean;
  reason?: string;
}
export interface IrNode {
  id: string;
  opcode:
    | (
        | "vehicle.read"
        | "vehicle.read_attribute"
        | "vehicle.write"
        | "vehicle.write_many"
        | "control.branch"
        | "control.switch"
        | "control.wait"
        | "control.wait_until"
        | "control.stable_for"
        | "control.repeat"
        | "control.while"
        | "control.parallel"
        | "control.stop"
        | "control.throttle"
        | "state.get"
        | "state.set"
        | "state.counter"
        | "state.filter"
        | "state.rate"
        | "unit.convert"
        | "type.cast"
        | "comm.log"
        | "comm.mqtt_publish"
        | "service.grpc_call"
      )
    | string;
  args: {
    [k: string]: IrArgValue | undefined;
  };
  next: {
    [k: string]: string | null;
  };
  body?: {
    entry: string | null;
  };
  outputs?: IrOutputs;
  src: IrSrc;
}
/**
 * Semantic block definition used by compiler, simulator and studio parity tests (ADR-0011 §4, analysis/05 §2). UI config lives in the studio and must match this spec.
 */
export interface BlockSpecV1 {
  specVersion: string & {
    [k: string]: unknown | undefined;
  };
  type: string;
  /**
   * blockVersion; bumped with a migration.
   */
  version: number;
  category: "triggers" | "sensors" | "actuators" | "attributes" | "logic" | "flow" | "state" | "comm" | "composite";
  title: string;
  priority?: "P0" | "P1" | "P2";
  /**
   * IR opcode this block lowers to, or `expr` for blocks inlined into expression trees (ADR-0014 §5).
   */
  opcode: string;
  /**
   * Allowed VSS kinds for the `path` prop (e.g. only actuator for sv_set_actuator).
   */
  vssKinds?: ("sensor" | "actuator" | "attribute")[];
  container?: boolean;
  concurrencyDefault?: "restart" | "ignore" | "queue" | "parallel";
  props: BlockSpecProp[];
  outputs: BlockSpecOutput[];
  handles: {
    in: string[];
    out: string[];
  };
  migrations?: {
    from: number;
    to: number;
  }[];
}
export interface BlockSpecProp {
  name: string;
  /**
   * Editor/semantic kind; maps to studio subBlock types (ADR-0011 §5).
   */
  kind:
    | "vss-path"
    | "expression"
    | "template"
    | "duration"
    | "enum"
    | "typed-value"
    | "integer"
    | "number"
    | "boolean"
    | "string"
    | "list";
  required: boolean;
  default?: unknown;
  /**
   * @minItems 1
   */
  enum?: [string | number | boolean, ...(string | number | boolean)[]];
  /**
   * Expected value type; `$signal` = datatype of the selected VSS path.
   */
  valueType?:
    | (
        | (
            | "boolean"
            | "int8"
            | "int16"
            | "int32"
            | "int64"
            | "uint8"
            | "uint16"
            | "uint32"
            | "uint64"
            | "float"
            | "double"
            | "string"
            | "boolean[]"
            | "int8[]"
            | "int16[]"
            | "int32[]"
            | "int64[]"
            | "uint8[]"
            | "uint16[]"
            | "uint32[]"
            | "uint64[]"
            | "float[]"
            | "double[]"
            | "string[]"
          )
        | ("duration" | "timestamp" | "json")
      )
    | "$signal";
  min?: number;
  max?: number;
  /**
   * Record shape for kind=list.
   */
  items?: BlockSpecProp[];
}
export interface BlockSpecOutput {
  name: string;
  /**
   * `$signal` = selected path datatype; `$element` = element type of the `array` prop; `$inferred` = typed by the expression.
   */
  type:
    | (
        | (
            | "boolean"
            | "int8"
            | "int16"
            | "int32"
            | "int64"
            | "uint8"
            | "uint16"
            | "uint32"
            | "uint64"
            | "float"
            | "double"
            | "string"
            | "boolean[]"
            | "int8[]"
            | "int16[]"
            | "int32[]"
            | "int64[]"
            | "uint8[]"
            | "uint16[]"
            | "uint32[]"
            | "uint64[]"
            | "float[]"
            | "double[]"
            | "string[]"
          )
        | ("duration" | "timestamp" | "json")
      )
    | ("$signal" | "$element" | "$inferred");
  /**
   * `$signal` = unit of the selected path.
   */
  unit?: string | null;
}
/**
 * Backend `POST /generate` result (ADR-0020, analysis/07 §2). Pure data: the workspace service is the only writer (ADR-0026). Every file path must be inside one of `ownedRoots`; the workspace re-validates.
 */
export interface GeneratedFileSetV1 {
  backend: string;
  runtimeVersion: string;
  files: GeneratedFile[];
  ownedRoots: OwnedRoots;
  /**
   * AppManifest fragment merged by the workspace (ADR-0023); shape owned by velocitas-stack and locked in M6/M7.
   */
  manifestFragment: {};
  sourceMaps: GeneratedSourceMap[];
  diagnostics: DiagnosticV1[];
}
export interface GeneratedFile {
  path: string & {
    [k: string]: unknown | undefined;
  };
  content: string;
  sha256: string;
  role: "source" | "header" | "test" | "build" | "config" | "doc";
}
export interface GeneratedSourceMap {
  file: string & {
    [k: string]: unknown | undefined;
  };
  ranges: {
    startLine: number;
    endLine: number;
    nodeId: string;
    blockId: string;
    workflowId: string;
  }[];
}
/**
 * Backend `GET /capabilities` = `backend.yaml` as JSON (ADR-0020, analysis/07 §1). Used by compiler stage S7.
 */
export interface BackendCapabilitiesV1 {
  id: string;
  name: string;
  version: string;
  language: "cpp" | "python" | "rust";
  /**
   * npm-style semver range, e.g. ">=1.0.0 <2.0.0".
   */
  irVersions: string;
  /**
   * npm-style semver range, e.g. ">=1.0.0 <2.0.0".
   */
  contracts: string;
  opcodes: (
    | ("event.app_start" | "event.signal_changed" | "event.timer" | "event.condition" | "event.mqtt_message")
    | (
        | (
            | "vehicle.read"
            | "vehicle.read_attribute"
            | "vehicle.write"
            | "vehicle.write_many"
            | "control.branch"
            | "control.switch"
            | "control.wait"
            | "control.wait_until"
            | "control.stable_for"
            | "control.repeat"
            | "control.while"
            | "control.parallel"
            | "control.stop"
            | "control.throttle"
            | "state.get"
            | "state.set"
            | "state.counter"
            | "state.filter"
            | "state.rate"
            | "unit.convert"
            | "type.cast"
            | "comm.log"
            | "comm.mqtt_publish"
            | "service.grpc_call"
          )
        | string
      )
  )[];
  features: {
    concurrencyPolicies: ("restart" | "ignore" | "queue" | "parallel")[];
    trace: boolean;
    sourceMaps: boolean;
  };
  runtime: {
    name: string;
    version: string;
    /**
     * Normalized POSIX path relative to the project root: no leading '/', no '..' or '.' segments, no backslash, no empty segment.
     */
    vendorPath: string;
  };
  toolchain: {
    id: string;
    template: string;
    templateSha: string;
  };
}
/**
 * Toolchain Agent job resource (`GET /jobs/:id`), ADR-0025 §2–4. Request body is `#/$defs/request`; stream lines are LogLine v1.
 */
export interface ToolchainJobV1 {
  id: string;
  kind: "init" | "deps" | "build" | "test" | "format-check" | "run" | "stop" | "generate-model";
  project: string;
  options?: ToolchainJobOptions;
  state: "queued" | "running" | "succeeded" | "failed" | "cancelled";
  exitCode?: number | null;
  /**
   * Wall-clock milliseconds since Unix epoch (logs/traces only, never inside IR or generated files).
   */
  createdAt?: number;
  /**
   * Wall-clock milliseconds since Unix epoch (logs/traces only, never inside IR or generated files).
   */
  startedAt?: number;
  /**
   * Wall-clock milliseconds since Unix epoch (logs/traces only, never inside IR or generated files).
   */
  finishedAt?: number;
  diagnostics?: DiagnosticV1[];
}
export interface ToolchainJobOptions {
  /**
   * build: `./build.sh -r`.
   */
  release?: boolean;
  /**
   * run: extra environment (keys are validated by the agent allowlist).
   */
  env?: {
    [k: string]: string | undefined;
  };
  /**
   * stop: job id of the run to stop.
   */
  runJobId?: string;
}
/**
 * Trace event as streamed to the studio (analysis/08 §3.1, ADR-0027). Produced identically by the simulator and by orchestrator TraceIngest from runtime `SVTRACE {…}` lines (`#/$defs/runtimeLine`).
 */
export interface TraceEventV1 {
  runId: string;
  seq: number;
  /**
   * ms; epoch for live runs, virtual clock for simulation.
   */
  ts: number;
  wf?: string;
  /**
   * Run instance number within the app.
   */
  run?: number;
  node?: string;
  blockId?: string;
  ev:
    | ("trigger" | "enter" | "exit" | "value" | "write" | "error" | "cancel")
    | ("app.started" | "app.stopping" | "vdb.connected" | "vdb.disconnected");
  data?: {};
}
/**
 * One log line of a job/run stream (analysis/08 §3.1, ADR-0025, ADR-0027). `runId` is the run or toolchain job id; `seq` is monotonic per stream (SSE Last-Event-ID).
 */
export interface LogLineV1 {
  runId: string;
  seq: number;
  /**
   * Wall-clock milliseconds since Unix epoch (logs/traces only, never inside IR or generated files).
   */
  ts: number;
  stream: "stdout" | "stderr" | "system";
  level: "debug" | "info" | "warn" | "error";
  msg: string;
  raw?: string;
}
/**
 * Server→client message of the signal-gateway WebSocket (analysis/08 §4, ADR-0024). Client messages: `#/$defs/clientMessage`.
 */
export interface SignalUpdateV1 {
  path: string;
  /**
   * Wall-clock milliseconds since Unix epoch (logs/traces only, never inside IR or generated files).
   */
  ts: number;
  value: JsonValue;
  /**
   * `value` = current value, `target` = actuator target (kuksa.val.v1).
   */
  field: "value" | "target";
}
/**
 * Input trace + expectations shared by simulator, runtime conformance, integration and parity tests (ADR-0017 §3–5, ADR-0042). Times are virtual ms from app start. Array values are JSON arrays; int64/uint64 are decimal strings (ADR-0018).
 */
export interface ScenarioV1 {
  scenarioVersion: string & {
    [k: string]: unknown | undefined;
  };
  name: string;
  description?: string;
  vss?: {
    release: string;
  };
  /**
   * ≤ 24 h virtual (ADR-0017 §5).
   */
  until: number;
  initial?: {
    [k: string]: JsonValue;
  };
  latency?: {
    read?: number;
    write?: number;
  };
  inputs: ScenarioInput[];
  expect?: {
    writes?: ScenarioWrite[];
    /**
     * Partial TraceEvent matchers (fields compared when present).
     */
    trace?: {}[];
  };
}
export interface ScenarioWrite {
  t: number;
  path: string;
  value: JsonValue;
}
/**
 * The only way the AI assistant changes a workflow (ADR-0030 §5, analysis/09 §5). `ref` is a temporary id mapped by the studio on apply; a stale `baseRevision` is rebased or rejected.
 */
export interface WorkflowPatchV1 {
  patchVersion: string & {
    [k: string]: unknown | undefined;
  };
  workflowId: string;
  baseRevision: number;
  /**
   * @minItems 1
   */
  ops: [WorkflowPatchOp, ...WorkflowPatchOp[]];
  rationale?: string;
}
/**
 * What one SynCode generation wrote (ADR-0026 §3.6, analysis/07 §3). The copy shipped inside generated code (`simvehicleapp.gen.json`) must be deterministic: it omits `generationId`/`project`, which only the workspace record (`.sv/generations/<slug>/<gid>.json`) carries. Used to detect GENERATED_FILE_MODIFIED.
 */
export interface GenerationManifestV1 {
  manifestVersion: string & {
    [k: string]: unknown | undefined;
  };
  generationId?: string;
  project?: string;
  backend: string;
  runtimeVersion: string;
  contracts: string;
  /**
   * @minItems 1
   */
  workflows: [GenerationWorkflow, ...GenerationWorkflow[]];
  ownedRoots: OwnedRoots;
  files: GenerationFileEntry[];
}
export interface GenerationWorkflow {
  workflowId: string;
  revision: number;
  /**
   * Prefixed content hash.
   */
  irHash: string;
}
export interface GenerationFileEntry {
  path: string & {
    [k: string]: unknown | undefined;
  };
  sha256: string;
  role?: "source" | "header" | "test" | "build" | "config" | "doc";
}
/**
 * Signed entitlement document (ADR-0031 §3–4): `SV_LICENSE_KEY` content and the `.simvehicleapp/license.json` shipped in exports. `signature` is base64 Ed25519 over the canonical JSON (sorted keys) of the document without `signature`. The orchestrator EntitlementService is the only decision point.
 */
export interface LicenseV1 {
  licenseVersion: string & {
    [k: string]: unknown | undefined;
  };
  /**
   * e.g. `full` (MVP), `community`.
   */
  edition: string;
  licensee: string;
  features: LicenseFeatures;
  limits: LicenseLimits;
  /**
   * Last valid day (UTC, YYYY-MM-DD) or null for no expiry.
   */
  expiry: string | null;
  /**
   * 64-byte Ed25519 signature, base64.
   */
  signature: string;
}
export interface LicenseFeatures {
  "export.source"?: boolean;
  /**
   * false ⇒ runtime exported as prebuilt static lib + headers.
   */
  "export.runtimeSource"?: boolean;
  "ai.assistant"?: boolean;
  "ide.access"?: boolean;
  syncode?: boolean;
  languages?: ("cpp" | "python" | "rust")[];
}
export interface LicenseLimits {
  maxProjects?: number;
}
/**
 * Body of `GET /version` that every service exposes (ADR-0007 §7). Health body: `#/$defs/health`.
 */
export interface ServiceInfoV1 {
  name: string;
  version: string;
  commit: string;
  contracts: string;
  /**
   * Service-specific extras, e.g. toolchain: velocitas CLI/SDK/conan versions, template SHA.
   */
  [k: string]: (string | number | boolean) | undefined;
}
/**
 * Response body for 422 and embedded diagnostic arrays.
 */
export interface DiagnosticList {
  diagnostics: DiagnosticV1[];
}
export interface IrExprConst {
  $const: unknown;
  /**
   * VSS datatypes plus internal types (ADR-0015 §1).
   */
  type:
    | (
        | "boolean"
        | "int8"
        | "int16"
        | "int32"
        | "int64"
        | "uint8"
        | "uint16"
        | "uint32"
        | "uint64"
        | "float"
        | "double"
        | "string"
        | "boolean[]"
        | "int8[]"
        | "int16[]"
        | "int32[]"
        | "int64[]"
        | "uint8[]"
        | "uint16[]"
        | "uint32[]"
        | "uint64[]"
        | "float[]"
        | "double[]"
        | "string[]"
      )
    | ("duration" | "timestamp" | "json");
  /**
   * VSS unit symbol (units.yaml key); null = dimensionless.
   */
  unit?: string | null;
}
/**
 * Output of a dominating trigger/node, e.g. `n1.value`.
 */
export interface IrExprRef {
  $ref: string;
}
/**
 * Latest cached value of a signal (`<Vehicle.Path>` reference).
 */
export interface IrExprSignal {
  $signal: string;
}
/**
 * Workflow variable (`<var.name>` reference).
 */
export interface IrExprState {
  $state: string;
}
export interface IrExprTemplate {
  $template: (string | IrExpr)[];
}
/**
 * Operator/function application. Operand keys are op-specific (l/r, a, cond/then/else, args, value/index/default); `to`/`type` may be plain strings for unit.convert/type.cast.
 */
export interface IrExprOp {
  $expr: {
    op: string;
    [k: string]: (IrExpr | IrExpr[] | string) | undefined;
  };
}
/**
 * Body of backend `POST /generate`.
 */
export interface GenerateRequest {
  project: {
    slug: string;
    appName: string;
    language: "cpp" | "python" | "rust";
    mqttTopicPrefix: string;
    traceLevel: "off" | "trigger" | "node";
  };
  /**
   * @minItems 1
   */
  workflows: [IRV1, ...IRV1[]];
  options?: {
    emitTests?: boolean;
  };
  /**
   * Scenario of a workflow for the generated tests (ADR-0022 §8, additive 2026-10-07); workflows without one get no test.
   *
   * @maxItems 1000
   */
  scenarios?: {
    workflowId: string;
    scenario: ScenarioV1;
  }[];
}
export interface ToolchainJobRequest {
  kind: "init" | "deps" | "build" | "test" | "format-check" | "run" | "stop" | "generate-model";
  project: string;
  options?: ToolchainJobOptions;
}
/**
 * JSON payload after the `SVTRACE ` prefix on one stdout line (ADR-0027 §3).
 */
export interface TraceRuntimeLine {
  v: 1;
  /**
   * Wall-clock milliseconds since Unix epoch (logs/traces only, never inside IR or generated files).
   */
  ts: number;
  app: string;
  wf?: string;
  run?: number;
  node?: string;
  ev:
    | ("trigger" | "enter" | "exit" | "value" | "write" | "error" | "cancel")
    | ("app.started" | "app.stopping" | "vdb.connected" | "vdb.disconnected");
  data?: {};
}
export interface ServiceHealth {
  status: "ok" | "degraded";
  checks?: {
    [k: string]: ("ok" | "fail") | undefined;
  };
}
