/**
 * M06-T10: `runtime/RUNTIME_API.md` generated from the doc comments of the public runtime headers
 * (ADR-0021). Vendored into every project with the runtime.
 *
 *   bun conformance/gen-runtime-api.ts           # write
 *   bun conformance/gen-runtime-api.ts --check   # exit 1 when the file is stale (CI)
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const RUNTIME = fileURLToPath(new URL("../../runtime/", import.meta.url));
const INCLUDE = join(RUNTIME, "include/simvehicleapp/rt");
const OUT = join(RUNTIME, "RUNTIME_API.md");

const HEADERS: Record<string, string> = {
  "Runtime.hpp": "Khai báo workflow (code sinh ra dùng), app, trace",
  "Value.hpp": "Giá trị, định dạng, ép kiểu, so sánh (ngữ nghĩa IR_SPEC)",
  "Strand.hpp": "Vòng sự kiện một luồng, đồng hồ",
  "Access.hpp": "Truy cập xe / MQTT (adapter thay được)",
  "Testing.hpp": "Mock vehicle/MQTT, chạy scenario, kiểm kỳ vọng",
  "Velocitas.hpp": "Adapter Velocitas SDK 0.7.1 và host `AppBase` (chỉ trong project)",
};

/** `/** … *\/` doc comments and the declaration that follows each one. */
function entries(text: string): { doc: string; decl: string }[] {
  const out: { doc: string; decl: string }[] = [];
  const re = /\/\*\*([\s\S]*?)\*\/\s*\n/g;
  for (const m of text.matchAll(re)) {
    // the declaration: everything up to the first `;` or `{`, on one line
    const rest = text.slice(m.index! + m[0].length);
    const end = rest.search(/[;{]/);
    const declText = (end < 0 ? rest : rest.slice(0, end)).replace(/\s+/g, " ");
    const doc = m[1]!
      .split("\n")
      .map((l) => l.replace(/^\s*\*\s?/, "").trimEnd())
      .join("\n")
      .trim();
    const decl = declText.trim();
    if (!decl || decl.startsWith("//") || decl.startsWith("#")) continue;
    out.push({ doc: doc.replace(/\s*\n\s*/g, " "), decl });
  }
  return out;
}

export function render(): string {
  const lines = [
    "# simvehicleapp-runtime-cpp — API",
    "",
    "<!-- Generated by compiler-code-cpp/generator/conformance/gen-runtime-api.ts from the runtime headers — do not edit. -->",
    "",
    `Phiên bản runtime: \`${readFileSync(join(RUNTIME, "VERSION"), "utf8").trim()}\` · namespace \`simvehicleapp::rt\` · C++17 · ADR-0021/0022.`,
    "",
    "Code trong `app/src/generated/` khai báo mỗi workflow bằng `rt::Workflow` (một câu lệnh cho mỗi trigger/node của IR);",
    "runtime thực thi chúng trên một strand với đúng ngữ nghĩa của simulator (ADR-0017 Notes). Code của bạn đặt trong",
    "`app/src/user/` (`UserHooks.*`) và không bao giờ bị SynCode ghi đè.",
    "",
  ];
  const present = readdirSync(INCLUDE).filter((f) => f.endsWith(".hpp")).sort();
  for (const h of Object.keys(HEADERS)) {
    if (!present.includes(h)) throw new Error(`missing header ${h}`);
    lines.push(`## \`simvehicleapp/rt/${h}\` — ${HEADERS[h]}`, "");
    for (const e of entries(readFileSync(join(INCLUDE, h), "utf8"))) {
      lines.push(`- \`${e.decl.replace(/`/g, "'")}\``, `  ${e.doc}`);
    }
    lines.push("");
  }
  const extra = present.filter((h) => !(h in HEADERS));
  if (extra.length) throw new Error(`document these headers: ${extra.join(", ")}`);
  return `${lines.join("\n").trimEnd()}\n`;
}

if (import.meta.main) {
  const text = render();
  if (process.argv.includes("--check")) {
    let have = "";
    try {
      have = readFileSync(OUT, "utf8");
    } catch {}
    if (have !== text) {
      console.log("RUNTIME_API.md is stale — run bun conformance/gen-runtime-api.ts");
      process.exit(1);
    }
    console.log("RUNTIME_API.md up to date");
  } else {
    writeFileSync(OUT, text);
    console.log(`wrote ${OUT}`);
  }
}
