#!/usr/bin/env python3
"""Module inventory and the release lock (ADR-0002 §3, ADR-0009 §5, M11-T10).

    scripts/modules.sh list                 modules with version and the git tree they are at
    scripts/modules.sh lock [--release X]   write simvehicleapp.lock.yaml from the committed tree
    scripts/modules.sh lock --check         exit 1 when simvehicleapp.lock.yaml is stale

Dev phase (one repo, ADR-0009): a module is pinned by the git **tree** SHA of `modules/<m>` in HEAD
(what `git subtree split` turns into the module repo). Release phase (submodules, ADR-0002): by the
submodule commit SHA (`git ls-tree HEAD modules/<m>` gives a commit). Image digests are recorded when
the images exist locally (`docker image inspect`), otherwise left out — `lock-verify` checks SHAs.
The lock is deterministic: same commit ⇒ same bytes.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "simvehicleapp.lock.yaml"
MODULES = sorted(p.name for p in (ROOT / "modules").iterdir() if p.is_dir())
IMAGES = {
    "simvehicleapp-contracts": ["contracts"],
    "simvehicleapp-core": ["vss-catalog", "compiler"],
    "simvehicleapp-orchestrator": ["orchestrator", "workspace", "signal-gateway"],
    "simvehicleapp-ai": ["ai-assistant"],
    "simvehicleapp-studio": ["studio", "studio-migrations", "studio-realtime"],
    "compiler-code-cpp": ["codegen-cpp"],
    "velocitas-stack": ["devcontainer-cpp", "toolchain-cpp"],
    "ide-vscode": ["ide-cpp"],
}


def git(*args: str) -> str:
    return subprocess.run(["git", *args], cwd=ROOT, check=True, capture_output=True, text=True).stdout.strip()


def pin(module: str, rev: str = "HEAD") -> tuple[str, str]:
    """(kind, sha): `tree` in the dev phase, `commit` when the module is a submodule."""
    out = git("ls-tree", rev, f"modules/{module}")
    if not out:
        return ("missing", "")
    mode, kind, sha = out.split()[0:3]
    return ("commit" if kind == "commit" else "tree", sha)


def version(module: str) -> str:
    d = ROOT / "modules" / module
    for f, read in (("package.json", lambda p: json.loads(p.read_text())["version"]), ("VERSION", lambda p: p.read_text().strip()), ("runtime/VERSION", lambda p: p.read_text().strip())):
        if (d / f).exists():
            try:
                return str(read(d / f))
            except (KeyError, ValueError):
                pass
    return "0.0.0"


def digest(image: str) -> str | None:
    try:
        out = subprocess.run(["docker", "image", "inspect", f"simvehicleapp/{image}:dev", "--format", "{{.Id}}"], capture_output=True, text=True, timeout=20)
    except (OSError, subprocess.TimeoutExpired):
        return None
    return out.stdout.strip() or None


def render(release: str, with_images: bool) -> str:
    contracts = json.loads((ROOT / "modules/simvehicleapp-contracts/package.json").read_text())["version"]
    lines = [
        "# SimVehicleApp release lock (ADR-0002 §3) — generated by scripts/modules.sh lock; verified by scripts/lock-verify.sh.",
        "lockVersion: 1",
        f"release: {release}",
        f"contracts: {contracts}",
        "modules:",
    ]
    for m in MODULES:
        kind, sha = pin(m)
        if kind == "missing":
            continue
        lines += [f"  {m}:", f"    path: modules/{m}", f"    {kind}: {sha}", f"    version: {version(m)}"]
        imgs = [(i, digest(i)) for i in IMAGES.get(m, [])] if with_images else []
        imgs = [(i, d) for i, d in imgs if d]
        if imgs:
            lines.append("    images:")
            lines += [f"      {i}: {d}" for i, d in imgs]
    return "\n".join(lines) + "\n"


def parse_lock(text: str) -> dict[str, dict[str, str]]:
    mods: dict[str, dict[str, str]] = {}
    cur = None
    for line in text.splitlines():
        if m := re.match(r"^  ([\w.-]+):$", line):
            cur = mods.setdefault(m.group(1), {})
        elif cur is not None and (m := re.match(r"^    (\w+): (\S+)$", line)):
            cur[m.group(1)] = m.group(2)
    return mods


def main(argv: list[str]) -> int:
    cmd = argv[0] if argv else "list"
    if cmd == "list":
        for m in MODULES:
            kind, sha = pin(m)
            print(f"{m:28} {version(m):16} {kind} {sha[:12]}")
        return 0
    if cmd == "lock":
        release = argv[argv.index("--release") + 1] if "--release" in argv else "dev"
        if "--check" in argv:
            if not LOCK.exists():
                print("simvehicleapp.lock.yaml is missing", file=sys.stderr)
                return 1
            current = parse_lock(LOCK.read_text())
            fresh = parse_lock(render(release, with_images=False))
            stale = [m for m in fresh if {k: v for k, v in current.get(m, {}).items() if k != "images"} != fresh[m]]
            if stale:
                print("lock is stale for: " + ", ".join(stale), file=sys.stderr)
                return 1
            print("lock up to date")
            return 0
        LOCK.write_text(render(release, with_images="--no-images" not in argv))
        print(f"wrote {LOCK.name} ({release})")
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
