import { commentText, cppString, snakeCase } from "./cpp.ts";
import { type CppExpr, ExprEmitter, ExprUse, type IrExpr } from "./expr.ts";
import { CodeWriter, lambda, type SourceRange } from "./writer.ts";

/**
 * One workflow (IR v1) ⇒ `workflows/<Class>.hpp/.cpp` (ADR-0022 §3, with Notes 2026-10-07): a
 * `bind(rt::Runtime&)` that declares every IR trigger and node as one runtime builder statement,
 * expressions as typed lambdas. Node ids, block ids and the order of declarations come from the IR,
 * so the same IR always gives the same bytes.
 */

export interface IrSignal {
  id: string;
  path: string;
  dataType: string;
}
export interface IrTopic {
  id: string;
  topic: string;
  direction: string;
}
export interface IrState {
  id: string;
  name: string;
  type: string;
  initial: unknown;
}
export interface IrTrigger {
  id: string;
  opcode: string;
  signal?: string;
  topic?: string;
  props: Record<string, unknown>;
  concurrency?: { policy: string; queueMax?: number; maxRuns?: number };
  outputs: Record<string, { type: string }>;
  entry: string | null;
  src: { blockId: string };
}
export interface IrNode {
  id: string;
  opcode: string;
  args: Record<string, unknown>;
  next: Record<string, string | null>;
  body?: { entry: string | null };
  outputs?: Record<string, { type: string }>;
  src: { blockId: string };
}
export interface WorkflowIr {
  irVersion: string;
  workflowId: string;
  workflowRevision: number;
  name: string;
  irHash: string;
  signals: IrSignal[];
  topics: IrTopic[];
  state: IrState[];
  triggers: IrTrigger[];
  nodes: IrNode[];
}

export const BACKEND_NAME = "compiler-code-cpp";
export const BACKEND_VERSION = "0.1.0";

/** Opcodes this backend implements (backend.yaml `opcodes`; the compiler's S7 checks them). */
export const OPCODES = [
  "event.app_start",
  "event.signal_changed",
  "event.timer",
  "event.condition",
  "event.mqtt_message",
  "vehicle.read",
  "vehicle.read_attribute",
  "vehicle.write",
  "control.branch",
  "control.switch",
  "control.wait",
  "control.wait_until",
  "control.stable_for",
  "control.repeat",
  "control.while",
  "control.parallel",
  "control.stop",
  "state.get",
  "state.set",
  "state.counter",
  "state.filter",
  "logic.eval",
  "logic.in_range",
  "comm.log",
  "comm.mqtt_publish",
] as const;

export class UnsupportedOpcode extends Error {
  constructor(
    readonly opcode: string,
    readonly nodeId: string,
    readonly blockId: string,
  ) {
    super(`opcode ${opcode} is not supported by ${BACKEND_NAME}`);
  }
}

export function headerComment(irHash: string): string {
  return `// Generated by SimVehicleApp ${BACKEND_NAME} ${BACKEND_VERSION} — DO NOT EDIT. irHash=${irHash}`;
}

const CHANGE: Record<string, string> = {
  any: "Any",
  rising: "Rising",
  falling: "Falling",
  crosses_above: "CrossesAbove",
  crosses_below: "CrossesBelow",
  becomes: "Becomes",
};
const POLICY: Record<string, string> = { restart: "Restart", ignore: "Ignore", queue: "Queue", parallel: "Parallel" };
const RESERVED = new Set(["c", "w", "rt", "runtime", "std"]);

/** C++ local names of a workflow's signals, topics and state (stable, readable, collision-free). */
export function localNames(ir: WorkflowIr): Map<string, string> {
  const names = new Map<string, string>();
  const used = new Set<string>(RESERVED);
  const take = (id: string, base: string) => {
    let n = base;
    if (used.has(n)) n = `${base}_${id}`;
    used.add(n);
    names.set(id, n);
  };
  for (const s of ir.signals) take(s.id, snakeCase(s.path.split(".").pop() ?? s.id));
  for (const t of ir.topics) take(t.id, `topic_${snakeCase(t.topic.split("/").filter(Boolean).pop() ?? t.id)}`);
  for (const v of ir.state) take(v.id, `state_${snakeCase(v.name)}`);
  return names;
}

export interface EmittedWorkflow {
  header: string;
  source: string;
  ranges: SourceRange[];
}

export function emitWorkflow(ir: WorkflowIr, className: string, headerPath: string): EmittedWorkflow {
  const names = localNames(ir);
  const signals = new Map(ir.signals.map((s) => [s.id, s]));
  const states = new Map(ir.state.map((v) => [v.id, v]));
  const outputs = new Map<string, Record<string, { type: string }>>();
  for (const t of ir.triggers) outputs.set(t.id, t.outputs);
  for (const n of ir.nodes) outputs.set(n.id, n.outputs ?? {});
  const env = {
    signalVar: (id: string) => ({ name: names.get(id)!, type: signals.get(id)!.dataType }),
    stateVar: (id: string) => ({ name: names.get(id)!, type: states.get(id)!.type }),
    outputType: (node: string, out: string) => {
      const t = outputs.get(node)?.[out]?.type;
      if (!t) throw new Error(`${node}.${out} has no declared type in the IR`);
      return t;
    },
  };

  /** A lambda over one expression; `wrap` turns the C++ expression into the returned value. */
  const fn = (e: unknown, wrap: (x: CppExpr, em: ExprEmitter) => string, asExpr: boolean): string => {
    const use = new ExprUse();
    const em = new ExprEmitter(env, use);
    const body = wrap(em.emit(e), em);
    const captures = [...use.captures].sort().join(", ");
    const l = lambda(body, captures, use.ctx ? "rt::Ctx& c" : "rt::Ctx&");
    return asExpr ? `rt::expr(${l})` : l;
  };
  const cond = (e: unknown) => (e === undefined ? "nullptr" : fn(e, (x) => x.code, false));
  const value = (e: unknown) => fn(e, (x) => x.code, true);
  const castValue = (e: unknown, to: string) => fn(e, (x, em) => em.castTo(x, to), true);
  const next = (n: Record<string, string | null>) =>
    `{${Object.keys(n)
      .sort()
      .map((h) => `{${cppString(h)}, ${cppString(n[h] ?? "")}}`)
      .join(", ")}}`;
  const nodeRef = (id: string, blockId: string) => `{${cppString(id)}, ${cppString(blockId)}}`;
  const concurrency = (c: IrTrigger["concurrency"]) =>
    `{rt::Policy::${POLICY[c?.policy ?? "parallel"] ?? "Parallel"}, ${Number(c?.queueMax ?? 8)}, ${Number(c?.maxRuns ?? 4)}}`;
  const outs = (o: Record<string, { type: string }>) =>
    `rt::Outputs{${Object.keys(o)
      .sort()
      .map((k) => `{${cppString(k)}, ${cppString(o[k]!.type)}}`)
      .join(", ")}}`;
  const num = (v: unknown) => String(Math.trunc(Number(v ?? 0)));
  /** A `double` literal (`0.5`, `1.0`, `1e-07`). */
  const real = (v: unknown) => {
    const s = String(Number(v ?? 0));
    return /[.eE]/.test(s) ? s : `${s}.0`;
  };
  const str = (v: string | null | undefined) => cppString(v ?? "");

  const w = new CodeWriter();
  w.line(headerComment(ir.irHash));
  w.line(`// Workflow "${commentText(ir.name)}" (${commentText(ir.workflowId)}, revision ${ir.workflowRevision}).`);
  w.line(`#include ${cppString(headerPath)}`);
  w.line();
  w.line('#include "simvehicleapp/rt/Runtime.hpp"');
  w.line();
  w.line("#include <cmath>");
  w.line("#include <optional>");
  w.line("#include <string>");
  w.line("#include <vector>");
  w.line();
  w.line("namespace simvehicleapp::generated {");
  w.line();
  w.block(`void ${className}::bind(rt::Runtime& runtime)`, () => {
    w.line(`auto& w = runtime.workflow(${cppString(ir.workflowId)}, ${cppString(className)});`);
    for (const s of ir.signals) {
      w.call(`const auto ${names.get(s.id)} = w.signal`, [cppString(s.id), cppString(s.path), cppString(s.dataType)]);
    }
    for (const t of ir.topics) w.call(`const auto ${names.get(t.id)} = w.topic`, [cppString(t.id), `rt::str(${cppString(t.topic)})`]);
    for (const v of ir.state) {
      w.call(`const auto ${names.get(v.id)} = w.state`, [cppString(v.id), cppString(v.type), `rt::Value::parse(${cppString(JSON.stringify(v.initial ?? null))})`]);
    }

    for (const t of ir.triggers) {
      w.line();
      w.node(ir.workflowId, t.id, t.src.blockId, () => {
        w.line(`// ${t.id} · ${t.opcode} · block ${commentText(t.src.blockId)}`);
        const id = nodeRef(t.id, t.src.blockId);
        const tail = [concurrency(t.concurrency), outs(t.outputs), str(t.entry)];
        const p = t.props;
        switch (t.opcode) {
          case "event.app_start":
            w.call("w.onAppStart", [id, ...tail]);
            break;
          case "event.signal_changed": {
            let threshold = "std::nullopt";
            if (p.threshold !== undefined) {
              const use = new ExprUse();
              const x = new ExprEmitter(env, use).emit(p.threshold);
              if (use.ctx) throw new Error(`${t.id}: a threshold must not depend on signals`);
              threshold = `rt::toValue(${x.code})`;
            }
            const mode = CHANGE[String(p.mode ?? "any")] ?? "Any";
            w.call("w.onSignalChanged", [id, names.get(t.signal!)!, `rt::Change::${mode}`, threshold, num(p.debounceMs), ...tail]);
            break;
          }
          case "event.timer":
            w.call("w.onTimer", [id, num(p.intervalMs), num(p.initialDelayMs), ...tail]);
            break;
          case "event.condition":
            w.call("w.onCondition", [id, cond(p.expr), num(p.debounceMs), ...tail]);
            break;
          case "event.mqtt_message":
            w.call("w.onMqtt", [id, names.get(t.topic!)!, p.payloadType === "json" ? "true" : "false", ...tail]);
            break;
          default:
            throw new UnsupportedOpcode(t.opcode, t.id, t.src.blockId);
        }
      });
    }

    for (const n of ir.nodes) {
      w.line();
      w.node(ir.workflowId, n.id, n.src.blockId, () => {
        w.line(`// ${n.id} · ${n.opcode} · block ${commentText(n.src.blockId)}`);
        const id = nodeRef(n.id, n.src.blockId);
        const a = n.args;
        const nx = next(n.next);
        switch (n.opcode) {
          case "vehicle.write": {
            const s = signals.get(String(a.signal))!;
            w.call("w.write", [id, names.get(s.id)!, castValue(a.value, s.dataType), a.awaitAck === false ? "false" : "true", a.onError === "stop" ? "rt::OnError::Stop" : "rt::OnError::Continue", nx]);
            break;
          }
          case "vehicle.read":
          case "vehicle.read_attribute":
            w.call("w.read", [id, names.get(String(a.signal))!, a.fresh === true ? "true" : "false", nx]);
            break;
          case "control.branch":
            w.call("w.branch", [id, cond(a.condition), nx]);
            break;
          case "control.switch":
            w.call("w.switchOn", [id, value(a.value), `{${((a.cases as unknown[]) ?? []).map(value).join(", ")}}`, nx]);
            break;
          case "control.wait":
            w.call("w.wait", [id, num(a.durationMs), nx]);
            break;
          case "control.wait_until":
            w.call("w.waitUntil", [id, cond(a.condition), num(a.timeoutMs), nx]);
            break;
          case "control.stable_for":
            w.call("w.stableFor", [id, cond(a.condition), num(a.durationMs), nx]);
            break;
          case "control.repeat":
            w.call("w.repeat", [id, num(a.count), num(a.intervalMs), str(n.body?.entry), nx]);
            break;
          case "control.while":
            w.call("w.whileLoop", [id, cond(a.condition), num(a.maxIterations), num(a.intervalMs), str(n.body?.entry), nx]);
            break;
          case "control.parallel": {
            const branches = ((a.branches as { entry: string | null }[]) ?? []).map((b) => str(b.entry));
            const join = a.join === "any" ? "Any" : a.join === "none" ? "None" : "All";
            w.call("w.parallel", [id, `{${branches.join(", ")}}`, `rt::Join::${join}`, nx]);
            break;
          }
          case "control.stop": {
            const scope = a.scope === "app" ? "App" : a.scope === "workflow" ? "Workflow" : "Run";
            w.call("w.stop", [id, `rt::StopScope::${scope}`, nx]);
            break;
          }
          case "state.get":
            w.call("w.stateGet", [id, names.get(String(a.state))!, nx]);
            break;
          case "state.set": {
            const v = states.get(String(a.state))!;
            w.call("w.stateSet", [id, names.get(v.id)!, castValue(a.value, v.type), nx]);
            break;
          }
          case "state.counter": {
            const op = a.op === "dec" ? "Dec" : a.op === "reset" ? "Reset" : "Inc";
            w.call("w.counter", [id, names.get(String(a.state))!, `rt::CounterOp::${op}`, num(a.step ?? 1), nx]);
            break;
          }
          case "logic.eval": {
            const out = Object.keys(n.outputs ?? {})[0] ?? "result";
            w.call("w.eval", [id, cppString(out), value(a.value), nx]);
            break;
          }
          case "state.filter": {
            const mode = a.mode === "exponential" ? "exponential" : a.mode === "median" ? "median" : "moving-average";
            w.call("w.filter", [id, value(a.value as IrExpr), cppString(mode), num(a.window ?? 1), real(a.alpha ?? 0), nx]);
            break;
          }
          case "logic.in_range":
            w.call("w.inRange", [id, value(a.value), value(a.low), value(a.high), a.mode === "hysteresis" ? "true" : "false", nx]);
            break;
          case "comm.log": {
            const level = a.level === undefined || a.level === null ? "std::nullopt" : `std::optional<std::string>(${cppString(String(a.level))})`;
            w.call("w.log", [id, level, value(a.message as IrExpr), nx]);
            break;
          }
          case "comm.mqtt_publish":
            w.call("w.publish", [id, names.get(String(a.topic))!, value(a.payload as IrExpr), nx]);
            break;
          default:
            throw new UnsupportedOpcode(n.opcode, n.id, n.src.blockId);
        }
      });
    }
  });
  w.line();
  w.line("} // namespace simvehicleapp::generated");

  const guard = `SIMVEHICLEAPP_GENERATED_${className.toUpperCase()}_HPP`;
  const h = new CodeWriter();
  h.line(headerComment(ir.irHash));
  h.line(`#ifndef ${guard}`);
  h.line(`#define ${guard}`);
  h.line();
  h.line("namespace simvehicleapp::rt {");
  h.line("class Runtime;");
  h.line("} // namespace simvehicleapp::rt");
  h.line();
  h.line("namespace simvehicleapp::generated {");
  h.line();
  h.line(`/** Workflow "${commentText(ir.name)}" (${commentText(ir.workflowId)}, revision ${ir.workflowRevision}). */`);
  h.block(`struct ${className}`, () => {
    h.line("/** Declares the workflow's triggers and steps on the runtime. */");
    h.line("static void bind(rt::Runtime& runtime);");
  }, "};");
  h.line();
  h.line("} // namespace simvehicleapp::generated");
  h.line();
  h.line(`#endif // ${guard}`);
  return { header: h.toString(), source: w.toString(), ranges: w.ranges };
}
