import { ExprEmitter, ExprUse, type IrExpr } from "./expr.ts";
import { atom, call, type Node, prefix } from "./layout.ts";
import { commentText, jsonNode, rsString, snakeCase } from "./rs.ts";
import { CodeWriter, type SourceRange } from "./writer.ts";

/**
 * One workflow (IR v1) ⇒ `workflows/<module>.rs` (ADR-0041, the layout of the C++ and Python backends): a
 * `bind(runtime)` that declares every IR trigger and node as one runtime builder call, expressions as
 * closures over the context `c`. Node ids, block ids and the order of declarations come from the IR, so
 * the same IR always gives the same bytes.
 */

export interface IrSignal {
  id: string;
  path: string;
  dataType: string;
}
export interface IrTopic {
  id: string;
  topic: string;
  direction: string;
}
export interface IrState {
  id: string;
  name: string;
  type: string;
  initial: unknown;
}
export interface IrTrigger {
  id: string;
  opcode: string;
  signal?: string;
  topic?: string;
  props: Record<string, unknown>;
  concurrency?: { policy: string; queueMax?: number; maxRuns?: number };
  outputs: Record<string, { type: string }>;
  entry: string | null;
  src: { blockId: string };
}
export interface IrNode {
  id: string;
  opcode: string;
  args: Record<string, unknown>;
  next: Record<string, string | null>;
  body?: { entry: string | null };
  outputs?: Record<string, { type: string }>;
  src: { blockId: string };
}
export interface WorkflowIr {
  irVersion: string;
  workflowId: string;
  workflowRevision: number;
  name: string;
  irHash: string;
  signals: IrSignal[];
  topics: IrTopic[];
  state: IrState[];
  triggers: IrTrigger[];
  nodes: IrNode[];
}

export const BACKEND_NAME = "compiler-code-rust";
export const BACKEND_VERSION = "0.1.0";

/** Opcodes this backend implements (backend.yaml `opcodes`; the compiler's S7 checks them). */
export const OPCODES = [
  "event.app_start",
  "event.signal_changed",
  "event.timer",
  "event.condition",
  "event.mqtt_message",
  "vehicle.read",
  "vehicle.read_attribute",
  "vehicle.write",
  "control.branch",
  "control.switch",
  "control.wait",
  "control.wait_until",
  "control.stable_for",
  "control.repeat",
  "control.while",
  "control.parallel",
  "control.stop",
  "state.get",
  "state.set",
  "state.counter",
  "logic.eval",
  "logic.in_range",
  "comm.log",
  "comm.mqtt_publish",
] as const;

export class UnsupportedOpcode extends Error {
  constructor(
    readonly opcode: string,
    readonly nodeId: string,
    readonly blockId: string,
  ) {
    super(`opcode ${opcode} is not supported by ${BACKEND_NAME}`);
  }
}

export function headerComment(hash: string): string {
  return `// Generated by SimVehicleApp ${BACKEND_NAME} ${BACKEND_VERSION} — DO NOT EDIT. irHash=${hash}`;
}

const MODES = new Set(["any", "rising", "falling", "crosses_above", "crosses_below", "becomes"]);
const POLICIES = new Set(["restart", "ignore", "queue", "parallel"]);

/** Rust local names of a workflow's signals, topics and state (stable, readable, collision-free). */
export function localNames(ir: WorkflowIr): Map<string, string> {
  const names = new Map<string, string>();
  const used = new Set<string>(["c", "w", "v", "runtime", "Runtime", "Value", "bind", "WORKFLOW_ID"]);
  const take = (id: string, base: string) => {
    let n = base;
    if (used.has(n)) n = `${base}_${id}`;
    used.add(n);
    names.set(id, n);
  };
  for (const s of ir.signals) take(s.id, snakeCase(s.path.split(".").pop() ?? s.id, "signal"));
  for (const t of ir.topics) take(t.id, `topic_${snakeCase(t.topic.split("/").filter(Boolean).pop() ?? t.id, "t")}`);
  for (const v of ir.state) take(v.id, `state_${snakeCase(v.name, "v")}`);
  return names;
}

export interface EmittedWorkflow {
  source: string;
  ranges: SourceRange[];
}

const slice = (items: Node[]): Node => prefix("&", { kind: "group", head: "", open: "[", items, close: "]", display: true });
const tuple = (items: Node[]): Node => ({ kind: "group", head: "", open: "(", items, close: ")", display: false });

export function emitWorkflow(ir: WorkflowIr): EmittedWorkflow {
  const names = localNames(ir);
  const signals = new Map(ir.signals.map((s) => [s.id, s]));
  const states = new Map(ir.state.map((v) => [v.id, v]));
  const outputs = new Map<string, Record<string, { type: string }>>();
  for (const t of ir.triggers) outputs.set(t.id, t.outputs);
  for (const n of ir.nodes) outputs.set(n.id, n.outputs ?? {});
  const env = {
    signal: (id: string) => ({ path: signals.get(id)!.path, type: signals.get(id)!.dataType }),
    stateType: (id: string) => states.get(id)!.type,
    outputType: (node: string, out: string) => {
      const t = outputs.get(node)?.[out]?.type;
      if (!t) throw new Error(`${node}.${out} has no declared type in the IR`);
      return t;
    },
  };

  /** `Box::new(|c: &Ctx| Ok(<expr>))` (the parameter named `_c` when the expression does not read it). */
  const closure = (wrapIt: (em: ExprEmitter) => Node): Node => {
    const use = new ExprUse();
    const body = wrapIt(new ExprEmitter(env, use));
    const param = use.ctx ? "c" : "_c";
    // A fallible call (`f(…)?`) is the closure's result as it is; any other value is wrapped in `Ok`.
    if (body.kind === "group" && body.close.endsWith("?")) return call("Box::new", [prefix(`|${param}: &Ctx| `, { ...body, close: body.close.slice(0, -1) })]);
    if (body.kind === "atom" && body.text.endsWith("?")) return call("Box::new", [atom(`|${param}: &Ctx| ${body.text.slice(0, -1)}`)]);
    return call("Box::new", [prefix(`|${param}: &Ctx| Ok(`, { kind: "group", head: "", open: "", items: [body], close: ")", display: false })]);
  };
  const cond = (e: unknown) => (e === undefined ? atom("None") : call("Some", [closure((em) => em.emit(e).code)]));
  const value = (e: unknown) => closure((em) => em.emit(e).code);
  const castValue = (e: unknown, to: string) => closure((em) => em.castTo(em.emit(e), to));
  const q = (s: string) => atom(rsString(s));
  const next = (n: Record<string, string | null>) =>
    slice(
      Object.keys(n)
        .sort()
        .map((h) => tuple([q(h), q(n[h] ?? "")])),
    );
  const nodeRef = (id: string, blockId: string) => tuple([q(id), q(blockId)]);
  const concurrency = (c: IrTrigger["concurrency"]) => {
    const policy = POLICIES.has(c?.policy ?? "") ? c!.policy : "parallel";
    return tuple([q(policy), atom(String(Math.trunc(Number(c?.queueMax ?? 8)))), atom(String(Math.trunc(Number(c?.maxRuns ?? 4))))]);
  };
  const outs = (o: Record<string, { type: string }>) =>
    slice(
      Object.keys(o)
        .sort()
        .map((k) => tuple([q(k), q(o[k]!.type)])),
    );
  const num = (v: unknown) => atom(String(Math.trunc(Number(v ?? 0))));
  const str = (v: string | null | undefined) => q(v ?? "");
  const local = (id: string) => atom(`&${names.get(id)!}`);
  const bool = (b: boolean) => atom(b ? "true" : "false");
  const stmt = (n: Node) => w.stmt({ ...(n as Node & { kind: "group" }), close: `${(n as { close: string }).close};` });

  const w = new CodeWriter();
  w.line(headerComment(ir.irHash));
  w.line(`//! Workflow "${commentText(ir.name)}" (${commentText(ir.workflowId)}, revision ${ir.workflowRevision}).`);
  w.line();
  w.line("#[allow(unused_imports)]");
  w.line("use simvehicleapp_runtime::values as v;");
  w.line("#[allow(unused_imports)]");
  w.line("use simvehicleapp_runtime::{Ctx, Runtime, Value};");
  w.line();
  w.line(`pub const WORKFLOW_ID: &str = ${rsString(ir.workflowId)};`);
  w.line();
  w.line("/// Declares the workflow's triggers and steps on the runtime.");
  w.line("#[rustfmt::skip]");
  w.line("#[allow(unused_variables)]");
  w.line("pub fn bind(runtime: &Runtime) {");
  w.indent(() => {
    w.line(`let w = runtime.workflow(${rsString(ir.workflowId)}, ${rsString(ir.name)});`);
    for (const s of ir.signals) stmt(prefix(`let ${names.get(s.id)} = `, call("w.signal", [q(s.id), q(s.path), q(s.dataType)])));
    for (const t of ir.topics) stmt(prefix(`let ${names.get(t.id)} = `, call("w.topic", [q(t.id), q(t.topic)])));
    for (const v of ir.state) stmt(prefix(`let ${names.get(v.id)} = `, call("w.state", [q(v.id), q(v.type), jsonNode(v.initial ?? null)])));

    for (const t of ir.triggers) {
      w.line();
      w.node(ir.workflowId, t.id, t.src.blockId, () => {
        w.line(`// ${t.id} · ${t.opcode} · block ${commentText(t.src.blockId)}`);
        const id = nodeRef(t.id, t.src.blockId);
        const tail = [concurrency(t.concurrency), outs(t.outputs), str(t.entry)];
        const p = t.props;
        switch (t.opcode) {
          case "event.app_start":
            stmt(call("w.on_app_start", [id, ...tail]));
            break;
          case "event.signal_changed": {
            let threshold: Node = atom("None");
            if (p.threshold !== undefined) {
              const use = new ExprUse();
              const x = new ExprEmitter(env, use).emit(p.threshold).code;
              if (use.ctx) throw new Error(`${t.id}: a threshold must not depend on signals`);
              // A constant: as it is; another constant expression is evaluated once at bind (`?` needs a Result).
              threshold = "$const" in (p.threshold as object) ? call("Some", [x]) : call("Some", [prefix("(|| -> simvehicleapp_runtime::R { Ok(", { kind: "group", head: "", open: "", items: [x], close: ") })().expect(\"constant threshold\")", display: false })]);
            }
            const mode = MODES.has(String(p.mode ?? "any")) ? String(p.mode ?? "any") : "any";
            stmt(call("w.on_signal_changed", [id, local(t.signal!), q(mode), threshold, num(p.debounceMs), ...tail]));
            break;
          }
          case "event.timer":
            stmt(call("w.on_timer", [id, num(p.intervalMs), num(p.initialDelayMs), ...tail]));
            break;
          case "event.condition":
            stmt(call("w.on_condition", [id, cond(p.expr), num(p.debounceMs), ...tail]));
            break;
          case "event.mqtt_message":
            stmt(call("w.on_mqtt", [id, local(t.topic!), bool(p.payloadType === "json"), ...tail]));
            break;
          default:
            throw new UnsupportedOpcode(t.opcode, t.id, t.src.blockId);
        }
      });
    }

    for (const n of ir.nodes) {
      w.line();
      w.node(ir.workflowId, n.id, n.src.blockId, () => {
        w.line(`// ${n.id} · ${n.opcode} · block ${commentText(n.src.blockId)}`);
        const id = nodeRef(n.id, n.src.blockId);
        const a = n.args;
        const nx = next(n.next);
        switch (n.opcode) {
          case "vehicle.write": {
            const s = signals.get(String(a.signal))!;
            stmt(call("w.write", [id, local(s.id), castValue(a.value, s.dataType), bool(a.awaitAck !== false), q(a.onError === "stop" ? "stop" : "continue"), nx]));
            break;
          }
          case "vehicle.read":
          case "vehicle.read_attribute":
            stmt(call("w.read", [id, local(String(a.signal)), bool(a.fresh === true), nx]));
            break;
          case "control.branch":
            stmt(call("w.branch", [id, cond(a.condition), nx]));
            break;
          case "control.switch":
            stmt(call("w.switch", [id, value(a.value), { ...call("vec!", ((a.cases as unknown[]) ?? []).map(value)), open: "[", close: "]" } as Node, nx]));
            break;
          case "control.wait":
            stmt(call("w.wait", [id, num(a.durationMs), nx]));
            break;
          case "control.wait_until":
            stmt(call("w.wait_until", [id, cond(a.condition), num(a.timeoutMs), nx]));
            break;
          case "control.stable_for":
            stmt(call("w.stable_for", [id, cond(a.condition), num(a.durationMs), nx]));
            break;
          case "control.repeat":
            stmt(call("w.repeat", [id, num(a.count), num(a.intervalMs), str(n.body?.entry), nx]));
            break;
          case "control.while":
            stmt(call("w.while_loop", [id, cond(a.condition), num(a.maxIterations), num(a.intervalMs), str(n.body?.entry), nx]));
            break;
          case "control.parallel": {
            const branches = ((a.branches as { entry: string | null }[]) ?? []).map((b) => str(b.entry));
            const join = a.join === "any" ? "any" : a.join === "none" ? "none" : "all";
            stmt(call("w.parallel", [id, slice(branches), q(join), nx]));
            break;
          }
          case "control.stop": {
            const scope = a.scope === "app" ? "app" : a.scope === "workflow" ? "workflow" : "run";
            stmt(call("w.stop", [id, q(scope), nx]));
            break;
          }
          case "state.get":
            stmt(call("w.state_get", [id, local(String(a.state)), nx]));
            break;
          case "state.set": {
            const v = states.get(String(a.state))!;
            stmt(call("w.state_set", [id, local(v.id), castValue(a.value, v.type), nx]));
            break;
          }
          case "state.counter": {
            const op = a.op === "dec" ? "dec" : a.op === "reset" ? "reset" : "inc";
            stmt(call("w.counter", [id, local(String(a.state)), q(op), num(a.step ?? 1), nx]));
            break;
          }
          case "logic.eval": {
            const out = Object.keys(n.outputs ?? {})[0] ?? "result";
            stmt(call("w.eval", [id, q(out), value(a.value), nx]));
            break;
          }
          case "logic.in_range":
            stmt(call("w.in_range", [id, value(a.value), value(a.low), value(a.high), bool(a.mode === "hysteresis"), nx]));
            break;
          case "comm.log": {
            const level = a.level === undefined || a.level === null ? atom("None") : call("Some", [q(String(a.level))]);
            stmt(call("w.log", [id, level, value(a.message as IrExpr), nx]));
            break;
          }
          case "comm.mqtt_publish":
            stmt(call("w.publish", [id, local(String(a.topic)), value(a.payload as IrExpr), nx]));
            break;
          default:
            throw new UnsupportedOpcode(n.opcode, n.id, n.src.blockId);
        }
      });
    }
  });
  w.line("}");
  return { source: w.toString(), ranges: w.ranges };
}
