import { createHash } from "node:crypto";
import { CONTRACTS_VERSION } from "@simvehicleapp/contracts";
import { BACKEND_NAME, BACKEND_VERSION, emitWorkflow, headerComment, type WorkflowIr } from "./emit.ts";
import { commentText, rsString, snakeCase } from "./rs.ts";
import { CodeWriter, type SourceRange } from "./writer.ts";

/**
 * A whole generation (ADR-0020 §2, ADR-0041): workflow modules, the app module the template's `main.rs` runs,
 * the generated scenario tests (a test target with its own harness printing gtest-style lines), source maps,
 * the generation manifest and the AppManifest fragment. Pure: same bytes for the same request.
 */

export const RUNTIME_VERSION = "0.1.0";
export const GENERATED = "app/src/generated/";
export const TESTS = "app/tests/generated/";
export const OWNED_ROOTS = [GENERATED, TESTS];

export interface GenerateRequest {
  project: { slug: string; appName: string; language: string; mqttTopicPrefix: string; traceLevel: "off" | "trigger" | "node" };
  workflows: WorkflowIr[];
  options?: { emitTests?: boolean };
  /** Scenario v1 per workflow for the generated tests (ADR-0022 §8). */
  scenarios?: { workflowId: string; scenario: Record<string, unknown> }[];
}

export interface FileOut {
  path: string;
  content: string;
  sha256: string;
  role: "source" | "header" | "test" | "build" | "config" | "doc";
}

export interface FileSet {
  backend: string;
  runtimeVersion: string;
  files: FileOut[];
  ownedRoots: string[];
  manifestFragment: Record<string, unknown>;
  sourceMaps: { file: string; ranges: SourceRange[] }[];
  diagnostics: never[];
}

const sha256 = (s: string) => createHash("sha256").update(s, "utf8").digest("hex");
const file = (path: string, content: string, role: FileOut["role"]): FileOut => ({ path, content, sha256: sha256(content), role });
const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;

/** Module names: snake_case of the workflow name; a clash gets the first 4 hex of sha256(workflowId). */
export function moduleNames(workflows: WorkflowIr[]): Map<string, string> {
  const out = new Map<string, string>();
  const used = new Set(["app", "workflows", "main", "mod", "generated"]);
  const sorted = [...workflows].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : a.workflowId < b.workflowId ? -1 : 1));
  for (const wf of sorted) {
    const base = snakeCase(wf.name, "workflow");
    let name = base;
    if (used.has(name)) name = `${base}_${sha256(wf.workflowId).slice(0, 4)}`;
    let n = 2;
    while (used.has(name)) name = `${base}_${n++}`;
    used.add(name);
    out.set(wf.workflowId, name);
  }
  return out;
}

export function generateProject(req: GenerateRequest): FileSet {
  const workflows = [...req.workflows].sort((a, b) => (a.workflowId < b.workflowId ? -1 : 1));
  const modules = moduleNames(workflows);
  const byName = [...workflows].sort((a, b) => (modules.get(a.workflowId)! < modules.get(b.workflowId)! ? -1 : 1));
  const files: FileOut[] = [];
  const sourceMaps: FileSet["sourceMaps"] = [];
  const projectHash = `sha256:${sha256(workflows.map((w) => w.irHash).join(","))}`;

  for (const wf of byName) {
    const mod = modules.get(wf.workflowId)!;
    const out = emitWorkflow(wf);
    const path = `${GENERATED}workflows/${mod}.rs`;
    files.push(file(path, out.source, "source"));
    sourceMaps.push({ file: path, ranges: out.ranges });
    files.push(file(`${GENERATED}sourcemap/${mod}.map.json`, json({ file: path, workflowId: wf.workflowId, irHash: wf.irHash, ranges: out.ranges }), "config"));
  }
  const header = headerComment(projectHash);
  files.push(file(`${GENERATED}mod.rs`, `${header}\n//! Code generated by SimVehicleApp from the project's workflows.\n\npub mod app;\npub mod workflows;\n`, "source"));
  files.push(
    file(
      `${GENERATED}workflows/mod.rs`,
      `${header}\n//! One module per workflow; each declares it on the runtime with \`bind\`.\n\n${byName.map((wf) => `pub mod ${modules.get(wf.workflowId)};\n`).join("")}`,
      "source",
    ),
  );

  // App module: what the template's main.rs runs.
  const signals = new Map<string, string>();
  for (const wf of workflows) for (const s of wf.signals) signals.set(s.path, s.dataType);
  const level = ["off", "trigger", "node"].includes(req.project.traceLevel) ? req.project.traceLevel : "node";
  const app = new CodeWriter();
  app.line(header);
  app.line(`//! The vehicle app ${commentText(req.project.appName)}: ${byName.length} workflow(s) on the SimVehicleApp runtime.`);
  app.line();
  app.line("use simvehicleapp_runtime::Runtime;");
  app.line();
  app.line("#[allow(unused_imports)]");
  app.line("use super::workflows;");
  app.line();
  app.line(`pub const APP_NAME: &str = ${rsString(req.project.appName)};`);
  app.line(`pub const TRACE_LEVEL: &str = ${rsString(level)};`);
  app.line();
  app.line("/// `bind` of every workflow, in a stable order.");
  app.line("#[rustfmt::skip]");
  app.line("pub const WORKFLOWS: &[fn(&Runtime)] = &[");
  for (const wf of byName) app.line(`    workflows::${modules.get(wf.workflowId)}::bind,`);
  app.line("];");
  app.line();
  app.line("/// VSS path ⇒ datatype of every signal the workflows use (checked against the project's VSS at build).");
  app.line("#[rustfmt::skip]");
  app.line("pub const SIGNALS: &[(&str, &str)] = &[");
  for (const p of [...signals.keys()].sort()) app.line(`    (${rsString(p)}, ${rsString(signals.get(p)!)}),`);
  app.line("];");
  files.push(file(`${GENERATED}app.rs`, app.toString(), "source"));

  // Generated tests: each workflow with a scenario runs it on the mock vehicle (ADR-0022 §8). The test target
  // has its own harness (`harness = false`) that prints gtest-style lines, like the other backends' tests.
  if (req.options?.emitTests) {
    const scenarios = new Map((req.scenarios ?? []).map((s) => [s.workflowId, s.scenario]));
    const t = new CodeWriter();
    t.line(header);
    t.line("//! Scenario tests of the workflows (contracts scenario v1), run on the mock vehicle and virtual clock.");
    t.line();
    t.line("use simvehicleapp_runtime::testing::{check_expectations, run_scenario};");
    t.line("use simvehicleapp_runtime::values::parse_json;");
    t.line();
    t.line("#[allow(unused_imports)]");
    t.line("use app::generated::workflows;");
    t.line();
    const tests: string[] = [];
    for (const wf of byName) {
      const sc = scenarios.get(wf.workflowId);
      if (!sc) continue;
      const mod = modules.get(wf.workflowId)!;
      t.line(`/// Scenario ${commentText(String(sc.name ?? ""))} of workflow ${commentText(wf.name)}.`);
      t.line(`const ${mod.toUpperCase()}: &str = ${rawString(JSON.stringify(sc, null, 2))};`);
      t.line();
      tests.push(mod);
    }
    t.line("/// The `bind` of a workflow.");
    t.line("type Bind = fn(&simvehicleapp_runtime::Runtime);");
    t.line();
    t.line("/// (suite, name, scenario, bind) of every generated test.");
    t.line("#[rustfmt::skip]");
    t.line("const TESTS: &[(&str, &str, &str, Bind)] = &[");
    for (const mod of tests) t.line(`    (${rsString(`${mod}Test`)}, "scenario_meets_its_expectations", ${mod.toUpperCase()}, workflows::${mod}::bind),`);
    t.line("];");
    t.line();
    t.lines_(`fn main() {
    let mut failed = Vec::new();
    for (suite, name, text, bind) in TESTS {
        println!("[ RUN      ] {suite}.{name}");
        let scenario = parse_json(text).expect("scenario JSON");
        let result = run_scenario(bind, &scenario, "sim", &[]);
        let problems = check_expectations(&result, scenario.get("expect"));
        if problems.is_empty() {
            println!("[       OK ] {suite}.{name} (0 ms)");
        } else {
            for p in &problems {
                println!("{p}");
            }
            println!("[  FAILED  ] {suite}.{name} (0 ms)");
            failed.push(format!("{suite}.{name}"));
        }
    }
    let n = TESTS.len();
    let s = |k: usize| if k == 1 { "" } else { "s" };
    println!(
        "[==========] {n} test{} from {n} test suite{} ran.",
        s(n),
        s(n)
    );
    println!(
        "[  PASSED  ] {} test{}.",
        n - failed.len(),
        s(n - failed.len())
    );
    for f in &failed {
        println!("[  FAILED  ] {f}");
    }
    if !failed.is_empty() {
        std::process::exit(1);
    }
}`);
    files.push(file(`${TESTS}main.rs`, t.toString(), "test"));
  }

  // Generation manifest shipped with the code: deterministic (no generationId/project, ADR-0026).
  const sorted = files.sort((a, b) => (a.path < b.path ? -1 : 1));
  const genManifest = {
    manifestVersion: "1.0.0",
    backend: `rust@${BACKEND_VERSION}`,
    runtimeVersion: RUNTIME_VERSION,
    contracts: CONTRACTS_VERSION,
    workflows: workflows.map((w) => ({ workflowId: w.workflowId, revision: w.workflowRevision, irHash: w.irHash })),
    ownedRoots: OWNED_ROOTS,
    files: sorted.map((f) => ({ path: f.path, sha256: f.sha256, role: f.role })),
  };
  sorted.push(file(`${GENERATED}simvehicleapp.gen.json`, json(genManifest), "config"));
  sorted.sort((a, b) => (a.path < b.path ? -1 : 1));

  return {
    backend: `rust@${BACKEND_VERSION}`,
    runtimeVersion: RUNTIME_VERSION,
    files: sorted,
    ownedRoots: OWNED_ROOTS,
    manifestFragment: manifestFragment(workflows),
    sourceMaps: sourceMaps.sort((a, b) => (a.file < b.file ? -1 : 1)),
    diagnostics: [],
  };
}

/** AppManifest v3 fragment (ADR-0023 §4): datapoints by path (write wins over read), MQTT topics. */
export function manifestFragment(workflows: WorkflowIr[]): Record<string, unknown> {
  const access = new Map<string, "read" | "write">();
  const reads = new Set<string>();
  const writes = new Set<string>();
  for (const wf of workflows) {
    for (const s of wf.signals) {
      const w = (s as { access?: string[] }).access?.includes("write");
      access.set(s.path, w || access.get(s.path) === "write" ? "write" : "read");
    }
    for (const t of wf.topics) (t.direction === "write" ? writes : reads).add(t.topic);
  }
  return {
    "vehicle-signal-interface": {
      required: [...access.keys()].sort().map((path) => ({ path, access: access.get(path)! })),
      provided: [],
    },
    pubsub: { reads: [...reads].sort(), writes: [...writes].sort() },
  };
}

/** A Rust raw string literal for `s` (enough `#` that its end cannot occur inside). */
export function rawString(s: string): string {
  let hashes = "#";
  while (s.includes(`"${hashes}`)) hashes += "#";
  return `r${hashes}"${s}"${hashes}`;
}
